CREATE TABLE IF NOT EXISTS `gw1_modifierdesc_de` (
	`id`      SMALLINT(3) UNSIGNED NOT NULL,
	`name`    TINYTEXT             NOT NULL,
	`desc`    TEXT                 NOT NULL,
	`base`    TINYTEXT             NOT NULL,
	`ext`     TINYTEXT             NOT NULL,
	PRIMARY KEY (`id`)
)
	ENGINE = InnoDB
	DEFAULT CHARSET = utf8mb4
	COLLATE = utf8mb4_bin;

INSERT INTO `gw1_modifierdesc_de` (`id`, `name`, `desc`, `base`, `ext`) VALUES
	(1, 'Eis-Axtstiel', '%s Kälte-Schaden', 'Axt', 'Eis'),
	(2, 'Ebon-Axtstiel', '%s Erd-Schaden', 'Axt', 'Ebon'),
	(3, 'Schock-Axtstiel', '%s Blitz-Schaden', 'Axt', 'Schock'),
	(4, 'Hitze-Axtstiel', '%s Feuer-Schaden', 'Axt', 'Hitze'),
	(5, 'Eis-Bogensehne', '%s Kälte-Schaden', 'Bogen', 'Eis'),
	(6, 'Ebon-Bogensehne', '%s Erd-Schaden', 'Bogen', 'Ebon'),
	(7, 'Schock-Bogensehne', '%s Blitz-Schaden', 'Bogen', 'Schock'),
	(8, 'Hitze-Bogensehne', '%s Feuer-Schaden', 'Bogen', 'Hitze'),
	(9, 'Eis-Hammerstiel', '%s Kälte-Schaden', 'Hammer', 'Eis'),
	(10, 'Ebon-Hammerstiel', '%s Erd-Schaden', 'Hammer', 'Ebon'),
	(11, 'Schock-Hammerstiel', '%s Blitz-Schaden', 'Hammer', 'Schock'),
	(12, 'Hitze-Hammerstiel', '%s Feuer-Schaden', 'Hammer', 'Hitze'),
	(13, 'Eis-Schwertheft', '%s Kälte-Schaden', 'Schwert', 'Eis'),
	(14, 'Ebon-Schwertheft', '%s Erd-Schaden', 'Schwert', 'Ebon'),
	(15, 'Schock-Schwertheft', '%s Blitz-Schaden', 'Schwert', 'Schock'),
	(16, 'Hitze-Schwertheft', '%s Feuer-Schaden', 'Schwert', 'Hitze'),
	(17, 'Zorn-Axtstiel', 'Doppeltes Adrenalin bei einem Treffer (Zufall: 10%)', 'Axt', 'Zorn'),
	(18, 'Zorn-Hammerstiel', 'Doppeltes Adrenalin bei einem Treffer (Zufall: 10%)', 'Hammer', 'Zorn'),
	(19, 'Zorn-Schwertheft', 'Doppeltes Adrenalin bei einem Treffer (Zufall: 10%)', 'Schwert', 'Zorn'),
	(22, 'Mesmer-Rune d. kleineren Schnellwirkung', 'Schnellwirkung +1 (Nicht stapelbar)', 'Mesmer-Rüstung', 'kleineren Schnellwirkung'),
	(23, 'Mesmer-Rune d. kleineren Beherrschungsmagie', 'Beherrschungsmagie +1 (Nicht stapelbar)', 'Mesmer-Rüstung', 'kleineren Beherrschungsmagie'),
	(24, 'Mesmer-Rune d. kleineren Illusionsmagie', 'Illusionsmagie +1 (Nicht stapelbar)', 'Mesmer-Rüstung', 'kleineren Illusionsmagie'),
	(25, 'Mesmer-Rune d. kleineren Inspirationsmagie', 'Inspirationsmagie +1 (Nicht stapelbar)', 'Mesmer-Rüstung', 'kleineren Inspirationsmagie'),
	(26, 'Nekromanten-Rune d. kleineren Blutmagie', 'Blutmagie +1 (Nicht stapelbar)', 'Nekromanten-Rüstung', 'kleineren Blutmagie'),
	(27, 'Nekromanten-Rune d. kleineren Todesmagie', 'Todesmagie +1 (Nicht stapelbar)', 'Nekromanten-Rüstung', 'kleineren Todesmagie'),
	(28, 'Nekromanten-Rune d. kleineren Flüche', 'Flüche +1 (Nicht stapelbar)', 'Nekromanten-Rüstung', 'kleineren Flüche'),
	(29, 'Nekromanten-Rune d. kleineren Seelensammlung', 'Seelensammlung +1 (Nicht stapelbar)', 'Nekromanten-Rüstung', 'kleineren Seelensammlung'),
	(30, 'Elementarmagier-Rune d. kleineren Energiespeicherung', 'Energiespeicherung +1 (Nicht stapelbar)', 'Elementarmagier-Rüstung', 'kleineren Energiespeicherung'),
	(31, 'Elementarmagier-Rune d. kleineren Feuermagie', 'Feuermagie +1 (Nicht stapelbar)', 'Elementarmagier-Rüstung', 'kleineren Feuermagie'),
	(32, 'Elementarmagier-Rune d. kleineren Luftmagie', 'Luftmagie +1 (Nicht stapelbar)', 'Elementarmagier-Rüstung', 'kleineren Luftmagie'),
	(33, 'Elementarmagier-Rune d. kleineren Erdmagie', 'Erdmagie +1 (Nicht stapelbar)', 'Elementarmagier-Rüstung', 'kleineren Erdmagie'),
	(34, 'Elementarmagier-Rune d. kleineren Wassermagie', 'Wassermagie +1 (Nicht stapelbar)', 'Elementarmagier-Rüstung', 'kleineren Wassermagie'),
	(35, 'Mönchs-Rune d. kleineren Heilgebete', 'Heilgebete +1 (Nicht stapelbar)', 'Mönchs-Rüstung', 'kleineren Heilgebete'),
	(36, 'Mönchs-Rune d. kleineren Peinigungsgebete', 'Peinigungsgebete +1 (Nicht stapelbar)', 'Mönchs-Rüstung', 'kleineren Peinigungsgebete'),
	(37, 'Mönchs-Rune d. kleineren Schutzgebete', 'Schutzgebete +1 (Nicht stapelbar)', 'Mönchs-Rüstung', 'kleineren Schutzgebete'),
	(38, 'Mönchs-Rune d. kleineren Gunst der Götter', 'Gunst der Götter +1 (Nicht stapelbar)', 'Mönchs-Rüstung', 'kleineren Gunst der Götter'),
	(39, 'Krieger-Rune d. kleineren Taktik', 'Taktik +1 (Nicht stapelbar)', 'Krieger-Rüstung', 'kleineren Taktik'),
	(40, 'Krieger-Rune d. kleineren Stärke', 'Stärke +1 (Nicht stapelbar)', 'Krieger-Rüstung', 'kleineren Stärke'),
	(41, 'Krieger-Rune d. kleineren Axtbeherrschung', 'Axtbeherrschung +1 (Nicht stapelbar)', 'Krieger-Rüstung', 'kleineren Axtbeherrschung'),
	(42, 'Krieger-Rune d. kleineren Hammerbeherrschung', 'Hammerbeherrschung +1 (Nicht stapelbar)', 'Krieger-Rüstung', 'kleineren Hammerbeherrschung'),
	(43, 'Krieger-Rune d. kleineren Schwertkunst', 'Schwertkunst +1 (Nicht stapelbar)', 'Krieger-Rüstung', 'kleineren Schwertkunst'),
	(44, 'Waldläufer-Rune d. kleineren Überleben in der Wildnis', 'Überleben in der Wildnis +1 (Nicht stapelbar)', 'Waldläufer-Rüstung', 'kleineren Überleben in der Wildnis'),
	(45, 'Waldläufer-Rune d. kleineren Fachkenntnis', 'Fachkenntnis +1 (Nicht stapelbar)', 'Waldläufer-Rüstung', 'kleineren Fachkenntnis'),
	(46, 'Waldläufer-Rune d. kleineren Tierbeherrschung', 'Tierbeherrschung +1 (Nicht stapelbar)', 'Waldläufer-Rüstung', 'kleineren Tierbeherrschung'),
	(47, 'Waldläufer-Rune d. kleineren Treffsicherheit', 'Treffsicherheit +1 (Nicht stapelbar)', 'Waldläufer-Rüstung', 'kleineren Treffsicherheit'),
	(48, 'Mesmer-Rune d. hohen Schnellwirkung', 'Schnellwirkung +2 (Nicht stapelbar)|Lebenspunkt -35', 'Mesmer-Rüstung', 'hohen Schnellwirkung'),
	(49, 'Mesmer-Rune d. hohen Beherrschungsmagie', 'Beherrschungsmagie +2 (Nicht stapelbar)|Lebenspunkt -35', 'Mesmer-Rüstung', 'hohen Beherrschungsmagie'),
	(50, 'Mesmer-Rune d. hohen Illusionsmagie', 'Illusionsmagie +2 (Nicht stapelbar)|Lebenspunkt -35', 'Mesmer-Rüstung', 'hohen Illusionsmagie'),
	(51, 'Mesmer-Rune d. hohen Inspirationsmagie', 'Inspirationsmagie +2 (Nicht stapelbar)|Lebenspunkt -35', 'Mesmer-Rüstung', 'hohen Inspirationsmagie'),
	(52, 'Nekromanten-Rune d. hohen Blutmagie', 'Blutmagie +2 (Nicht stapelbar)|Lebenspunkt -35', 'Nekromanten-Rüstung', 'hohen Blutmagie'),
	(53, 'Nekromanten-Rune d. hohen Todesmagie', 'Todesmagie +2 (Nicht stapelbar)|Lebenspunkt -35', 'Nekromanten-Rüstung', 'hohen Todesmagie'),
	(54, 'Nekromanten-Rune d. hohen Flüche', 'Flüche +2 (Nicht stapelbar)|Lebenspunkt -35', 'Nekromanten-Rüstung', 'hohen Flüche'),
	(55, 'Nekromanten-Rune d. hohen Seelensammlung', 'Seelensammlung +2 (Nicht stapelbar)|Lebenspunkt -35', 'Nekromanten-Rüstung', 'hohen Seelensammlung'),
	(56, 'Elementarmagier-Rune d. hohen Energiespeicherung', 'Energiespeicherung +2 (Nicht stapelbar)|Lebenspunkt -35', 'Elementarmagier-Rüstung', 'hohen Energiespeicherung'),
	(57, 'Elementarmagier-Rune d. hohen Feuermagie', 'Feuermagie +2 (Nicht stapelbar)|Lebenspunkt -35', 'Elementarmagier-Rüstung', 'hohen Feuermagie'),
	(58, 'Elementarmagier-Rune d. hohen Luftmagie', 'Luftmagie +2 (Nicht stapelbar)|Lebenspunkt -35', 'Elementarmagier-Rüstung', 'hohen Luftmagie'),
	(59, 'Elementarmagier-Rune d. hohen Erdmagie', 'Erdmagie +2 (Nicht stapelbar)|Lebenspunkt -35', 'Elementarmagier-Rüstung', 'hohen Erdmagie'),
	(60, 'Elementarmagier-Rune d. hohen Wassermagie', 'Wassermagie +2 (Nicht stapelbar)|Lebenspunkt -35', 'Elementarmagier-Rüstung', 'hohen Wassermagie'),
	(61, 'Mönchs-Rune d. hohen Heilgebete', 'Heilgebete +2 (Nicht stapelbar)|Lebenspunkt -35', 'Mönchs-Rüstung', 'hohen Heilgebete'),
	(62, 'Mönchs-Rune d. hohen Peinigungsgebete', 'Peinigungsgebete +2 (Nicht stapelbar)|Lebenspunkt -35', 'Mönchs-Rüstung', 'hohen Peinigungsgebete'),
	(63, 'Mönchs-Rune d. hohen Schutzgebete', 'Schutzgebete +2 (Nicht stapelbar)|Lebenspunkt -35', 'Mönchs-Rüstung', 'hohen Schutzgebete'),
	(64, 'Mönchs-Rune d. hohen Gunst der Götter', 'Gunst der Götter +2 (Nicht stapelbar)|Lebenspunkt -35', 'Mönchs-Rüstung', 'hohen Gunst der Götter'),
	(65, 'Krieger-Rune d. hohen Taktik', 'Taktik +2 (Nicht stapelbar)|Lebenspunkt -35', 'Krieger-Rüstung', 'hohen Taktik'),
	(66, 'Krieger-Rune d. hohen Stärke', 'Stärke +2 (Nicht stapelbar)|Lebenspunkt -35', 'Krieger-Rüstung', 'hohen Stärke'),
	(67, 'Krieger-Rune d. hohen Axtbeherrschung', 'Axtbeherrschung +2 (Nicht stapelbar)|Lebenspunkt -35', 'Krieger-Rüstung', 'hohen Axtbeherrschung'),
	(68, 'Krieger-Rune d. hohen Hammerbeherrschung', 'Hammerbeherrschung +2 (Nicht stapelbar)|Lebenspunkt -35', 'Krieger-Rüstung', 'hohen Hammerbeherrschung'),
	(69, 'Krieger-Rune d. hohen Schwertkunst', 'Schwertkunst +2 (Nicht stapelbar)|Lebenspunkt -35', 'Krieger-Rüstung', 'hohen Schwertkunst'),
	(70, 'Waldläufer-Rune d. hohen Überleben in der Wildnis', 'Überleben in der Wildnis +2 (Nicht stapelbar)|Lebenspunkt -35', 'Waldläufer-Rüstung', 'hohen Überleben in der Wildnis'),
	(71, 'Waldläufer-Rune d. hohen Fachkenntnis', 'Fachkenntnis +2 (Nicht stapelbar)|Lebenspunkt -35', 'Waldläufer-Rüstung', 'hohen Fachkenntnis'),
	(72, 'Waldläufer-Rune d. hohen Tierbeherrschung', 'Tierbeherrschung +2 (Nicht stapelbar)|Lebenspunkt -35', 'Waldläufer-Rüstung', 'hohen Tierbeherrschung'),
	(73, 'Waldläufer-Rune d. hohen Treffsicherheit', 'Treffsicherheit +2 (Nicht stapelbar)|Lebenspunkt -35', 'Waldläufer-Rüstung', 'hohen Treffsicherheit'),
	(74, 'Mesmer-Rune d. überlegenen Schnellwirkung', 'Schnellwirkung +3 (Nicht stapelbar)|Lebenspunkt -75', 'Mesmer-Rüstung', 'überlegenen Schnellwirkung'),
	(75, 'Mesmer-Rune d. überlegenen Beherrschungsmagie', 'Beherrschungsmagie +3 (Nicht stapelbar)|Lebenspunkt -75', 'Mesmer-Rüstung', 'überlegenen Beherrschungsmagie'),
	(76, 'Mesmer-Rune d. überlegenen Illusionsmagie', 'Illusionsmagie +3 (Nicht stapelbar)|Lebenspunkt -75', 'Mesmer-Rüstung', 'überlegenen Illusionsmagie'),
	(77, 'Mesmer-Rune d. überlegenen Inspirationsmagie', 'Inspirationsmagie +3 (Nicht stapelbar)|Lebenspunkt -75', 'Mesmer-Rüstung', 'überlegenen Inspirationsmagie'),
	(78, 'Nekromanten-Rune d. überlegenen Blutmagie', 'Blutmagie +3 (Nicht stapelbar)|Lebenspunkt -75', 'Nekromanten-Rüstung', 'überlegenen Blutmagie'),
	(79, 'Nekromanten-Rune d. überlegenen Todesmagie', 'Todesmagie +3 (Nicht stapelbar)|Lebenspunkt -75', 'Nekromanten-Rüstung', 'überlegenen Todesmagie'),
	(80, 'Nekromanten-Rune d. überlegenen Flüche', 'Flüche +3 (Nicht stapelbar)|Lebenspunkt -75', 'Nekromanten-Rüstung', 'überlegenen Flüche'),
	(81, 'Nekromanten-Rune d. überlegenen Seelensammlung', 'Seelensammlung +3 (Nicht stapelbar)|Lebenspunkt -75', 'Nekromanten-Rüstung', 'überlegenen Seelensammlung'),
	(82, 'Elementarmagier-Rune d. überlegenen Energiespeicherung', 'Energiespeicherung +3 (Nicht stapelbar)|Lebenspunkt -75', 'Elementarmagier-Rüstung', 'überlegenen Energiespeicherung'),
	(83, 'Elementarmagier-Rune d. überlegenen Feuermagie', 'Feuermagie +3 (Nicht stapelbar)|Lebenspunkt -75', 'Elementarmagier-Rüstung', 'überlegenen Feuermagie'),
	(84, 'Elementarmagier-Rune d. überlegenen Luftmagie', 'Luftmagie +3 (Nicht stapelbar)|Lebenspunkt -75', 'Elementarmagier-Rüstung', 'überlegenen Luftmagie'),
	(85, 'Elementarmagier-Rune d. überlegenen Erdmagie', 'Erdmagie +3 (Nicht stapelbar)|Lebenspunkt -75', 'Elementarmagier-Rüstung', 'überlegenen Erdmagie'),
	(86, 'Elementarmagier-Rune d. überlegenen Wassermagie', 'Wassermagie +3 (Nicht stapelbar)|Lebenspunkt -75', 'Elementarmagier-Rüstung', 'überlegenen Wassermagie'),
	(87, 'Mönchs-Rune d. überlegenen Heilgebete', 'Heilgebete +3 (Nicht stapelbar)|Lebenspunkt -75', 'Mönchs-Rüstung', 'überlegenen Heilgebete'),
	(88, 'Mönchs-Rune d. überlegenen Peinigungsgebete', 'Peinigungsgebete +3 (Nicht stapelbar)|Lebenspunkt -75', 'Mönchs-Rüstung', 'überlegenen Peinigungsgebete'),
	(89, 'Mönchs-Rune d. überlegenen Schutzgebete', 'Schutzgebete +3 (Nicht stapelbar)|Lebenspunkt -75', 'Mönchs-Rüstung', 'überlegenen Schutzgebete'),
	(90, 'Mönchs-Rune d. überlegenen Gunst der Götter', 'Gunst der Götter +3 (Nicht stapelbar)|Lebenspunkt -75', 'Mönchs-Rüstung', 'überlegenen Gunst der Götter'),
	(91, 'Krieger-Rune d. überlegenen Taktik', 'Taktik +3 (Nicht stapelbar)|Lebenspunkt -75', 'Krieger-Rüstung', 'überlegenen Taktik'),
	(92, 'Krieger-Rune d. überlegenen Stärke', 'Stärke +3 (Nicht stapelbar)|Lebenspunkt -75', 'Krieger-Rüstung', 'überlegenen Stärke'),
	(93, 'Krieger-Rune d. überlegenen Axtbeherrschung', 'Axtbeherrschung +3 (Nicht stapelbar)|Lebenspunkt -75', 'Krieger-Rüstung', 'überlegenen Axtbeherrschung'),
	(94, 'Krieger-Rune d. überlegenen Hammerbeherrschung', 'Hammerbeherrschung +3 (Nicht stapelbar)|Lebenspunkt -75', 'Krieger-Rüstung', 'überlegenen Hammerbeherrschung'),
	(95, 'Krieger-Rune d. überlegenen Schwertkunst', 'Schwertkunst +3 (Nicht stapelbar)|Lebenspunkt -75', 'Krieger-Rüstung', 'überlegenen Schwertkunst'),
	(96, 'Waldläufer-Rune d. überlegenen Überleben in der Wildnis', 'Überleben in der Wildnis +3 (Nicht stapelbar)|Lebenspunkt -75', 'Waldläufer-Rüstung', 'überlegenen Überleben in der Wildnis'),
	(97, 'Waldläufer-Rune d. überlegenen Fachkenntnis', 'Fachkenntnis +3 (Nicht stapelbar)|Lebenspunkt -75', 'Waldläufer-Rüstung', 'überlegenen Fachkenntnis'),
	(98, 'Waldläufer-Rune d. überlegenen Tierbeherrschung', 'Tierbeherrschung +3 (Nicht stapelbar)|Lebenspunkt -75', 'Waldläufer-Rüstung', 'überlegenen Tierbeherrschung'),
	(99, 'Waldläufer-Rune d. überlegenen Treffsicherheit', 'Treffsicherheit +3 (Nicht stapelbar)|Lebenspunkt -75', 'Waldläufer-Rüstung', 'überlegenen Treffsicherheit'),
	(100, 'Verteidigungs-Stabkopf', 'Rüstung +5', 'Stab', 'Verteidigungs'),
	(101, 'Stachel-Axtstiel', 'Erhöht von Euch zugefügte Blutung-Dauer um 33% und eine weitere Sekunde (Stapelbar)', 'Axt', 'Stachel'),
	(102, 'Stachel-Schwertheft', 'Erhöht von Euch zugefügte Blutung-Dauer um 33% und eine weitere Sekunde (Stapelbar)', 'Schwert', 'Stachel'),
	(103, 'Verkrüppelungs-Axtstiel', 'Erhöht von Euch zugefügte Verkrüppelung-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Axt', 'Verkrüppelungs'),
	(104, 'Verkrüppelungs-Schwertheft', 'Erhöht von Euch zugefügte Verkrüppelung-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Schwert', 'Verkrüppelungs'),
	(105, 'Grausamkeits-Axtstiel', 'Erhöht von Euch zugefügte Tiefe Wunde-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Axt', 'Grausamkeits'),
	(106, 'Grausamkeits-Hammerstiel', 'Erhöht von Euch zugefügte Tiefe Wunde-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Hammer', 'Grausamkeits'),
	(107, 'Grausamkeits-Schwertheft', 'Erhöht von Euch zugefügte Tiefe Wunde-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Schwert', 'Grausamkeits'),
	(108, 'Einblick-Stabkopf', 'Energie +5', 'Stab', 'Einblick'),
	(109, 'Rüstigkeits-Stabkopf', 'Lebenspunkte +30', 'Stab', 'Rüstigkeits'),
	(110, 'Gift-Axtstiel', 'Erhöht von Euch zugefügte Gift-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Axt', 'Gift'),
	(111, 'Gift-Bogensehne', 'Erhöht von Euch zugefügte Gift-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Bogen', 'Gift'),
	(112, 'Gift-Schwertheft', 'Erhöht von Euch zugefügte Gift-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Schwert', 'Gift'),
	(113, 'Schwergewichts-Axtstiel', 'Erhöht von Euch zugefügte Schwäche-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Axt', 'Schwergewichts'),
	(114, 'Schwergewichts-Hammerstiel', 'Erhöht von Euch zugefügte Schwäche-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Hammer', 'Schwergewichts'),
	(115, 'Eifer-Axtstiel', 'Energiegewinn bei Treffer: 1|Regeneration von Energiepunkten: -1', 'Axt', 'Eifer'),
	(116, 'Eifer-Hammerstiel', 'Energiegewinn bei Treffer: 1|Regeneration von Energiepunkten: -1', 'Hammer', 'Eifer'),
	(117, 'Eifer-Bogensehne', 'Energiegewinn bei Treffer: 1|Regeneration von Energiepunkten: -1', 'Bogen', 'Eifer'),
	(118, 'Eifer-Schwertheft', 'Energiegewinn bei Treffer: 1|Regeneration von Energiepunkten: -1', 'Schwert', 'Eifer'),
	(119, 'Vampir-Axtstiel', 'Lebenspunkte entziehen: 3|Regeneration von Lebenspunkten: -1', 'Axt', 'Vampir'),
	(120, 'Vampir-Hammerstiel', 'Lebenspunkte entziehen: 5|Regeneration von Lebenspunkten: -1', 'Hammer', 'Vampir'),
	(121, 'Vampir-Bogensehne', 'Lebenspunkte entziehen: 5|Regeneration von Lebenspunkten: -1', 'Bogen', 'Vampir'),
	(122, 'Vampir-Schwertheft', 'Lebenspunkte entziehen: 3|Regeneration von Lebenspunkten: -1', 'Schwert', 'Vampir'),
	(123, 'Derwisch-Rune d. kleineren Mystik', 'Mystik +1 (Nicht stapelbar)', 'Derwisch-Rüstung', 'kleineren Mystik'),
	(124, 'Derwisch-Rune d. kleineren Erdgebete', 'Erdgebete +1 (Nicht stapelbar)', 'Derwisch-Rüstung', 'kleineren Erdgebete'),
	(125, 'Derwisch-Rune d. kleineren Sensenbeherrschung', 'Sensenbeherrschung +1 (Nicht stapelbar)', 'Derwisch-Rüstung', 'kleineren Sensenbeherrschung'),
	(126, 'Derwisch-Rune d. kleineren Windgebete', 'Windgebete +1 (Nicht stapelbar)', 'Derwisch-Rüstung', 'kleineren Windgebete'),
	(127, 'Axtgriff d. Verteidigung', 'Rüstung +5', 'Axt', 'Verteidigung'),
	(128, 'Bogengriff d. Verteidigung', 'Rüstung +5', 'Bogen', 'Verteidigung'),
	(129, 'Axtgriff d. Abwehr', 'Rüstung +7 (gg. Elementarschaden)', 'Axt', 'Abwehr'),
	(130, 'Bogengriff d. Abwehr', 'Rüstung +7 (gg. Elementarschaden)', 'Bogen', 'Abwehr'),
	(131, 'Hammergriff d. Abwehr', 'Rüstung +7 (gg. Elementarschaden)', 'Hammer', 'Abwehr'),
	(132, 'Stabhülle d. Abwehr', 'Rüstung +7 (gg. Elementarschaden)', 'Stab', 'Abwehr'),
	(133, 'Schwertknauf d. Abwehr', 'Rüstung +7 (gg. Elementarschaden)', 'Schwert', 'Abwehr'),
	(134, 'Hammergriff d. Verteidigung', 'Rüstung +5', 'Hammer', 'Verteidigung'),
	(135, 'Axtgriff d. Zuflucht', 'Rüstung +7 (gg. körperlichen Schaden)', 'Axt', 'Zuflucht'),
	(136, 'Bogengriff d. Zuflucht', 'Rüstung +7 (gg. körperlichen Schaden)', 'Bogen', 'Zuflucht'),
	(137, 'Hammergriff d. Zuflucht', 'Rüstung +7 (gg. körperlichen Schaden)', 'Hammer', 'Zuflucht'),
	(138, 'Stabhülle d. Zuflucht', 'Rüstung +7 (gg. körperlichen Schaden)', 'Stab', 'Zuflucht'),
	(139, 'Schwertknauf d. Zuflucht', 'Rüstung +7 (gg. körperlichen Schaden)', 'Schwert', 'Zuflucht'),
	(140, 'Stabhülle d. Verteidigung', 'Rüstung +5', 'Stab', 'Verteidigung'),
	(141, 'Schwertknauf d. Verteidigung', 'Rüstung +5', 'Schwert', 'Verteidigung'),
	(142, 'Axtgriff d. Tapferkeit', 'Lebenspunkte +30', 'Axt', 'Tapferkeit'),
	(143, 'Bogengriff d. Tapferkeit', 'Lebenspunkte +30', 'Bogen', 'Tapferkeit'),
	(144, 'Hammergriff d. Tapferkeit', 'Lebenspunkte +30', 'Hammer', 'Tapferkeit'),
	(145, 'Stabhülle d. Tapferkeit', 'Lebenspunkte +30', 'Stab', 'Tapferkeit'),
	(146, 'Schwertknauf d. Tapferkeit', 'Lebenspunkte +30', 'Schwert', 'Tapferkeit'),
	(147, 'Axtgriff d. Verzauberung', 'Verlängert Verzauberungen um 20%', 'Axt', 'Verzauberung'),
	(148, 'Bogengriff d. Verzauberung', 'Verlängert Verzauberungen um 20%', 'Bogen', 'Verzauberung'),
	(149, 'Hammergriff d. Verzauberung', 'Verlängert Verzauberungen um 20%', 'Hammer', 'Verzauberung'),
	(150, 'Stabhülle d. Verzauberung', 'Verlängert Verzauberungen um 20%', 'Stab', 'Verzauberung'),
	(151, 'Schwertknauf d. Verzauberung', 'Verlängert Verzauberungen um 20%', 'Schwert', 'Verzauberung'),
	(152, 'Axtgriff d. Axtbeherrschung', 'Gegenstandsattribut +1 (20%ige Chance bei Verwendung von Fertigkeiten)', 'Axt', 'Axtbeherrschung'),
	(153, 'Bogengriff d. Treffsicherheit', 'Gegenstandsattribut +1 (20%ige Chance bei Verwendung von Fertigkeiten)', 'Bogen', 'Treffsicherheit'),
	(154, 'Hammergriff d. Hammerbeherrschung', 'Gegenstandsattribut +1 (20%ige Chance bei Verwendung von Fertigkeiten)', 'Hammer', 'Hammerbeherrschung'),
	(155, 'Schwertknauf d. Schwertkunst', 'Gegenstandsattribut +1 (20%ige Chance bei Verwendung von Fertigkeiten)', 'Schwert', 'Schwertkunst'),
	(156, 'Rune d. kleineren Lebenskraft', 'Lebenspunkte +30 (Nicht stapelbar)', 'Rüstung', 'kleineren Lebenskraft'),
	(157, 'Rune d. hohen Lebenskraft', 'Lebenspunkte +41 (Nicht stapelbar)', 'Rüstung', 'hohen Lebenskraft'),
	(158, 'Rune d. überlegenen Lebenskraft', 'Lebenspunkte +50 (Nicht stapelbar)', 'Rüstung', 'überlegenen Lebenskraft'),
	(159, 'Krieger-Rune d. kleineren Absorption', 'Reduziert physischen Schaden um 1. (Nicht stapelbar)', 'Krieger-Rüstung', 'kleineren Absorption'),
	(160, 'Krieger-Rune d. hohen Absorption', 'Reduziert physischen Schaden um 2. (Nicht stapelbar)', 'Krieger-Rüstung', 'hohen Absorption'),
	(161, 'Krieger-Rune d. überlegenen Absorption', 'Reduziert physischen Schaden um 3. (Nicht stapelbar)', 'Krieger-Rüstung', 'überlegenen Absorption'),
	(162, 'Assassinen-Rune d. kleineren Kritische Stöße', 'Kritische Stöße +1 (Nicht stapelbar)', 'Assassinen-Rüstung', 'kleineren Kritische Stöße'),
	(163, 'Assassinen-Rune d. kleineren Dolchbeherrschung', 'Dolchbeherrschung +1 (Nicht stapelbar)', 'Assassinen-Rüstung', 'kleineren Dolchbeherrschung'),
	(164, 'Assassinen-Rune d. kleineren Tödliche Künste', 'Tödliche Künste +1 (Nicht stapelbar)', 'Assassinen-Rüstung', 'kleineren Tödliche Künste'),
	(165, 'Assassinen-Rune d. kleineren Schattenkünste', 'Schattenkünste +1 (Nicht stapelbar)', 'Assassinen-Rüstung', 'kleineren Schattenkünste'),
	(166, 'Ritualisten-Rune d. kleineren Kanalisierungsmagie', 'Kanalisierungsmagie +1 (Nicht stapelbar)', 'Ritualisten-Rüstung', 'kleineren Kanalisierungsmagie'),
	(167, 'Ritualisten-Rune d. kleineren Wiederherstellungsmagie', 'Wiederherstellungsmagie +1 (Nicht stapelbar)', 'Ritualisten-Rüstung', 'kleineren Wiederherstellungsmagie'),
	(168, 'Ritualisten-Rune d. kleineren Zwiesprache', 'Zwiesprache +1 (Nicht stapelbar)', 'Ritualisten-Rüstung', 'kleineren Zwiesprache'),
	(169, 'Ritualisten-Rune d. kleineren Macht des Herbeirufens', 'Macht des Herbeirufens +1 (Nicht stapelbar)', 'Ritualisten-Rüstung', 'kleineren Macht des Herbeirufens'),
	(170, 'Assassinen-Rune d. hohen Kritische Stöße', 'Kritische Stöße +2 (Nicht stapelbar)|Lebenspunkt -35', 'Assassinen-Rüstung', 'hohen Kritische Stöße'),
	(171, 'Assassinen-Rune d. hohen Dolchbeherrschung', 'Dolchbeherrschung +2 (Nicht stapelbar)|Lebenspunkt -35', 'Assassinen-Rüstung', 'hohen Dolchbeherrschung'),
	(172, 'Assassinen-Rune d. hohen Tödliche Künste', 'Tödliche Künste +2 (Nicht stapelbar)|Lebenspunkt -35', 'Assassinen-Rüstung', 'hohen Tödliche Künste'),
	(173, 'Assassinen-Rune d. hohen Schattenkünste', 'Schattenkünste +2 (Nicht stapelbar)|Lebenspunkt -35', 'Assassinen-Rüstung', 'hohen Schattenkünste'),
	(174, 'Ritualisten-Rune d. hohen Kanalisierungsmagie', 'Kanalisierungsmagie +2 (Nicht stapelbar)|Lebenspunkt -35', 'Ritualisten-Rüstung', 'hohen Kanalisierungsmagie'),
	(175, 'Ritualisten-Rune d. hohen Wiederherstellungsmagie', 'Wiederherstellungsmagie +2 (Nicht stapelbar)|Lebenspunkt -35', 'Ritualisten-Rüstung', 'hohen Wiederherstellungsmagie'),
	(176, 'Ritualisten-Rune d. hohen Zwiesprache', 'Zwiesprache +2 (Nicht stapelbar)|Lebenspunkt -35', 'Ritualisten-Rüstung', 'hohen Zwiesprache'),
	(177, 'Ritualisten-Rune d. hohen Macht des Herbeirufens', 'Macht des Herbeirufens +2 (Nicht stapelbar)|Lebenspunkt -35', 'Ritualisten-Rüstung', 'hohen Macht des Herbeirufens'),
	(178, 'Assassinen-Rune d. überlegenen Kritische Stöße', 'Kritische Stöße +3 (Nicht stapelbar)|Lebenspunkt -75', 'Assassinen-Rüstung', 'überlegenen Kritische Stöße'),
	(179, 'Assassinen-Rune d. überlegenen Dolchbeherrschung', 'Dolchbeherrschung +3 (Nicht stapelbar)|Lebenspunkt -75', 'Assassinen-Rüstung', 'überlegenen Dolchbeherrschung'),
	(180, 'Assassinen-Rune d. überlegenen Tödliche Künste', 'Tödliche Künste +3 (Nicht stapelbar)|Lebenspunkt -75', 'Assassinen-Rüstung', 'überlegenen Tödliche Künste'),
	(181, 'Assassinen-Rune d. überlegenen Schattenkünste', 'Schattenkünste +3 (Nicht stapelbar)|Lebenspunkt -75', 'Assassinen-Rüstung', 'überlegenen Schattenkünste'),
	(182, 'Ritualisten-Rune d. überlegenen Kanalisierungsmagie', 'Kanalisierungsmagie +3 (Nicht stapelbar)|Lebenspunkt -75', 'Ritualisten-Rüstung', 'überlegenen Kanalisierungsmagie'),
	(183, 'Ritualisten-Rune d. überlegenen Wiederherstellungsmagie', 'Wiederherstellungsmagie +3 (Nicht stapelbar)|Lebenspunkt -75', 'Ritualisten-Rüstung', 'überlegenen Wiederherstellungsmagie'),
	(184, 'Ritualisten-Rune d. überlegenen Zwiesprache', 'Zwiesprache +3 (Nicht stapelbar)|Lebenspunkt -75', 'Ritualisten-Rüstung', 'überlegenen Zwiesprache'),
	(185, 'Ritualisten-Rune d. überlegenen Macht des Herbeirufens', 'Macht des Herbeirufens +3 (Nicht stapelbar)|Lebenspunkt -75', 'Ritualisten-Rüstung', 'überlegenen Macht des Herbeirufens'),
	(186, 'Eis-Dolchangel', '%s Kälte-Schaden', 'Dolche', 'Eis'),
	(187, 'Ebon-Dolchangel', '%s Erd-Schaden', 'Dolche', 'Ebon'),
	(188, 'Hitze-Dolchangel', '%s Feuer-Schaden', 'Dolche', 'Hitze'),
	(189, 'Schock-Dolchangel', '%s Blitz-Schaden', 'Dolche', 'Schock'),
	(190, 'Eifer-Dolchangel', 'Energiegewinn bei Treffer: 1|Regeneration von Energiepunkten: -1', 'Dolche', 'Eifer'),
	(191, 'Vampir-Dolchangel', 'Lebenspunkte entziehen: 3|Regeneration von Lebenspunkten: -1', 'Dolche', 'Vampir'),
	(192, 'Stachel-Dolchangel', 'Erhöht von Euch zugefügte Blutung-Dauer um 33% und eine weitere Sekunde (Stapelbar)', 'Dolche', 'Stachel'),
	(193, 'Verkrüppelungs-Dolchangel', 'Erhöht von Euch zugefügte Verkrüppelung-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Dolche', 'Verkrüppelungs'),
	(194, 'Grausamkeits-Dolchangel', 'Erhöht von Euch zugefügte Tiefe Wunde-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Dolche', 'Grausamkeits'),
	(195, 'Gift-Dolchangel', 'Erhöht von Euch zugefügte Gift-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Dolche', 'Gift'),
	(196, 'Dämpfungs-Dolchangel', 'Erhöht von Euch zugefügte Benommenheit-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Dolche', 'Dämpfungs'),
	(197, 'Zorn-Dolchangel', 'Doppeltes Adrenalin bei einem Treffer (Zufall: 10%)', 'Dolche', 'Zorn'),
	(198, 'Paragon-Rune d. kleineren Führung', 'Führung +1 (Nicht stapelbar)', 'Paragon-Rüstung', 'kleineren Führung'),
	(199, 'Dolchgriff d. Beherrschung', 'Gegenstandsattribut +1 (20%ige Chance bei Verwendung von Fertigkeiten)', 'Dolche', 'Beherrschung'),
	(200, 'Dolchgriff d. Verteidigung', 'Rüstung +5', 'Dolche', 'Verteidigung'),
	(201, 'Dolchgriff d. Zuflucht', 'Rüstung +7 (gg. körperlichen Schaden)', 'Dolche', 'Zuflucht'),
	(202, 'Dolchgriff d. Abwehr', 'Rüstung +7 (gg. Elementarschaden)', 'Dolche', 'Abwehr'),
	(203, 'Dolchgriff d. Verzauberung', 'Verlängert Verzauberungen um 20%', 'Dolche', 'Verzauberung'),
	(204, 'Dolchgriff d. Tapferkeit', 'Lebenspunkte +30', 'Dolche', 'Tapferkeit'),
	(205, 'Stachel-Bogensehne', 'Erhöht von Euch zugefügte Blutung-Dauer um 33% und eine weitere Sekunde (Stapelbar)', 'Bogen', 'Stachel'),
	(206, 'Verkrüppelungs-Bogensehne', 'Erhöht von Euch zugefügte Verkrüppelung-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Bogen', 'Verkrüppelungs'),
	(207, 'Dämpfungs-Bogensehne', 'Erhöht von Euch zugefügte Benommenheit-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Bogen', 'Dämpfungs'),
	(208, 'Trenn-Axtstiel', 'Rüstungsdurchdringung +20% (Zufall: 20%)', 'Axt', 'Trenn'),
	(209, 'Trenn-Bogensehne', 'Rüstungsdurchdringung +20% (Zufall: 20%)', 'Bogen', 'Trenn'),
	(210, 'Trenn-Hammerstiel', 'Rüstungsdurchdringung +20% (Zufall: 20%)', 'Hammer', 'Trenn'),
	(211, 'Trenn-Schwertheft', 'Rüstungsdurchdringung +20% (Zufall: 20%)', 'Schwert', 'Trenn'),
	(212, 'Trenn-Dolchangel', 'Rüstungsdurchdringung +20% (Zufall: 20%)', 'Dolche', 'Trenn'),
	(213, 'Paragon-Rune d. kleineren Motivation', 'Motivation +1 (Nicht stapelbar)', 'Paragon-Rüstung', 'kleineren Motivation'),
	(214, 'Paragon-Rune d. kleineren Befehlsgewalt', 'Befehlsgewalt +1 (Nicht stapelbar)', 'Paragon-Rüstung', 'kleineren Befehlsgewalt'),
	(215, 'Paragon-Rune d. kleineren Speerbeherrschung', 'Speerbeherrschung +1 (Nicht stapelbar)', 'Paragon-Rüstung', 'kleineren Speerbeherrschung'),
	(216, 'Derwisch-Rune d. hohen Mystik', 'Mystik +2 (Nicht stapelbar)|Lebenspunkt -35', 'Derwisch-Rüstung', 'hohen Mystik'),
	(217, 'Derwisch-Rune d. hohen Erdgebete', 'Erdgebete +2 (Nicht stapelbar)|Lebenspunkt -35', 'Derwisch-Rüstung', 'hohen Erdgebete'),
	(218, 'Derwisch-Rune d. hohen Sensenbeherrschung', 'Sensenbeherrschung +2 (Nicht stapelbar)|Lebenspunkt -35', 'Derwisch-Rüstung', 'hohen Sensenbeherrschung'),
	(219, 'Derwisch-Rune d. hohen Windgebete', 'Windgebete +2 (Nicht stapelbar)|Lebenspunkt -35', 'Derwisch-Rüstung', 'hohen Windgebete'),
	(220, 'Paragon-Rune d. hohen Führung', 'Führung +2 (Nicht stapelbar)|Lebenspunkt -35', 'Paragon-Rüstung', 'hohen Führung'),
	(221, 'Paragon-Rune d. hohen Motivation', 'Motivation +2 (Nicht stapelbar)|Lebenspunkt -35', 'Paragon-Rüstung', 'hohen Motivation'),
	(222, 'Paragon-Rune d. hohen Befehlsgewalt', 'Befehlsgewalt +2 (Nicht stapelbar)|Lebenspunkt -35', 'Paragon-Rüstung', 'hohen Befehlsgewalt'),
	(223, 'Paragon-Rune d. hohen Speerbeherrschung', 'Speerbeherrschung +2 (Nicht stapelbar)|Lebenspunkt -35', 'Paragon-Rüstung', 'hohen Speerbeherrschung'),
	(224, 'Derwisch-Rune d. überlegenen Mystik', 'Mystik +3 (Nicht stapelbar)|Lebenspunkt -75', 'Derwisch-Rüstung', 'überlegenen Mystik'),
	(225, 'Derwisch-Rune d. überlegenen Erdgebete', 'Erdgebete +3 (Nicht stapelbar)|Lebenspunkt -75', 'Derwisch-Rüstung', 'überlegenen Erdgebete'),
	(226, 'Derwisch-Rune d. überlegenen Sensenbeherrschung', 'Sensenbeherrschung +3 (Nicht stapelbar)|Lebenspunkt -75', 'Derwisch-Rüstung', 'überlegenen Sensenbeherrschung'),
	(227, 'Derwisch-Rune d. überlegenen Windgebete', 'Windgebete +3 (Nicht stapelbar)|Lebenspunkt -75', 'Derwisch-Rüstung', 'überlegenen Windgebete'),
	(228, 'Paragon-Rune d. überlegenen Führung', 'Führung +3 (Nicht stapelbar)|Lebenspunkt -75', 'Paragon-Rüstung', 'überlegenen Führung'),
	(229, 'Paragon-Rune d. überlegenen Motivation', 'Motivation +3 (Nicht stapelbar)|Lebenspunkt -75', 'Paragon-Rüstung', 'überlegenen Motivation'),
	(230, 'Paragon-Rune d. überlegenen Befehlsgewalt', 'Befehlsgewalt +3 (Nicht stapelbar)|Lebenspunkt -75', 'Paragon-Rüstung', 'überlegenen Befehlsgewalt'),
	(231, 'Paragon-Rune d. überlegenen Speerbeherrschung', 'Speerbeherrschung +3 (Nicht stapelbar)|Lebenspunkt -75', 'Paragon-Rüstung', 'überlegenen Speerbeherrschung'),
	(232, 'Eis-Sensenstiel', '%s Kälte-Schaden', 'Sense', 'Eis'),
	(233, 'Ebon-Sensenstiel', '%s Erd-Schaden', 'Sense', 'Ebon'),
	(234, 'Eifer-Sensenstiel', 'Energiegewinn bei Treffer: 1|Regeneration von Energiepunkten: -1', 'Sense', 'Eifer'),
	(235, 'Vampir-Sensenstiel', 'Lebenspunkte entziehen: 3|Regeneration von Lebenspunkten: -1', 'Sense', 'Vampir'),
	(236, 'Trenn-Sensenstiel', 'Rüstungsdurchdringung +20% (Zufall: 20%)', 'Sense', 'Trenn'),
	(237, 'Stachel-Sensenstiel', 'Erhöht von Euch zugefügte Blutung-Dauer um 33% und eine weitere Sekunde (Stapelbar)', 'Sense', 'Stachel'),
	(238, 'Verkrüppelungs-Sensenstiel', 'Erhöht von Euch zugefügte Verkrüppelung-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Sense', 'Verkrüppelungs'),
	(239, 'Grausamkeits-Sensenstiel', 'Erhöht von Euch zugefügte Tiefe Wunde-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Sense', 'Grausamkeits'),
	(240, 'Zorn-Sensenstiel', 'Doppeltes Adrenalin bei einem Treffer (Zufall: 10%)', 'Sense', 'Zorn'),
	(241, 'Gift-Sensenstiel', 'Erhöht von Euch zugefügte Gift-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Sense', 'Gift'),
	(242, 'Schwergewichts-Sensenstiel', 'Erhöht von Euch zugefügte Schwäche-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Sense', 'Schwergewichts'),
	(243, 'Sensengriff d. Sensenbeherrschung', 'Gegenstandsattribut +1 (20%ige Chance bei Verwendung von Fertigkeiten)', 'Sense', 'Sensenbeherrschung'),
	(244, 'Sensengriff d. Verteidigung', 'Rüstung +5', 'Sense', 'Verteidigung'),
	(245, 'Sensengriff d. Zuflucht', 'Rüstung +7 (gg. körperlichen Schaden)', 'Sense', 'Zuflucht'),
	(246, 'Sensengriff d. Abwehr', 'Rüstung +7 (gg. Elementarschaden)', 'Sense', 'Abwehr'),
	(247, 'Sensengriff d. Verzauberung', 'Verlängert Verzauberungen um 20%', 'Sense', 'Verzauberung'),
	(248, 'Sensengriff d. Tapferkeit', 'Lebenspunkte +30', 'Sense', 'Tapferkeit'),
	(249, 'Hitze-Speerspitze', '%s Feuer-Schaden', 'Speer', 'Hitze'),
	(250, 'Schock-Speerspitze', '%s Blitz-Schaden', 'Speer', 'Schock'),
	(251, 'Eifer-Speerspitze', 'Energiegewinn bei Treffer: 1|Regeneration von Energiepunkten: -1', 'Speer', 'Eifer'),
	(252, 'Vampir-Speerspitze', 'Lebenspunkte entziehen: 3|Regeneration von Lebenspunkten: -1', 'Speer', 'Vampir'),
	(253, 'Trenn-Speerspitze', 'Rüstungsdurchdringung +20% (Zufall: 20%)', 'Speer', 'Trenn'),
	(254, 'Stachel-Speerspitze', 'Erhöht von Euch zugefügte Blutung-Dauer um 33% und eine weitere Sekunde (Stapelbar)', 'Speer', 'Stachel'),
	(255, 'Verkrüppelungs-Speerspitze', 'Erhöht von Euch zugefügte Verkrüppelung-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Speer', 'Verkrüppelungs'),
	(256, 'Grausamkeits-Speerspitze', 'Erhöht von Euch zugefügte Tiefe Wunde-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Speer', 'Grausamkeits'),
	(257, 'Zorn-Speerspitze', 'Doppeltes Adrenalin bei einem Treffer (Zufall: 10%)', 'Speer', 'Zorn'),
	(258, 'Gift-Speerspitze', 'Erhöht von Euch zugefügte Gift-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Speer', 'Gift'),
	(259, 'Dämpfungs-Speerspitze', 'Erhöht von Euch zugefügte Benommenheit-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Speer', 'Dämpfungs'),
	(260, 'Schwergewichts-Speerspitze', 'Erhöht von Euch zugefügte Schwäche-Dauer um 33% (Stapelbar)|Erhöht von Euch zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Speer', 'Schwergewichts'),
	(261, 'Speergriff d. Speerbeherrschung', 'Gegenstandsattribut +1 (20%ige Chance bei Verwendung von Fertigkeiten)', 'Speer', 'Speerbeherrschung'),
	(262, 'Speergriff d. Verteidigung', 'Rüstung +5', 'Speer', 'Verteidigung'),
	(263, 'Speergriff d. Zuflucht', 'Rüstung +7 (gg. körperlichen Schaden)', 'Speer', 'Zuflucht'),
	(264, 'Speergriff d. Abwehr', 'Rüstung +7 (gg. Elementarschaden)', 'Speer', 'Abwehr'),
	(265, 'Speergriff d. Verzauberung', 'Verlängert Verzauberungen um 20%', 'Speer', 'Verzauberung'),
	(266, 'Speergriff d. Tapferkeit', 'Lebenspunkte +30', 'Speer', 'Tapferkeit'),
	(267, 'Fokus-Kern d. Ausdauer', 'Lebenspunkte +45 (während eine Haltung eingenommen wird)', 'Fokus', 'Ausdauer'),
	(268, 'Fokus-Kern d. Wertschätzung', 'Lebenspunkte +60 (bei Verhexung)', 'Fokus', 'Wertschätzung'),
	(269, 'Hitze-Sensenstiel', '%s Feuer-Schaden', 'Sense', 'Hitze'),
	(270, 'Schock-Sensenstiel', '%s Blitz-Schaden', 'Sense', 'Schock'),
	(271, 'Eis-Speerspitze', '%s Kälte-Schaden', 'Speer', 'Eis'),
	(272, 'Ebon-Speerspitze', '%s Erd-Schaden', 'Speer', 'Ebon'),
	(273, 'Schnelligkeits-Stabkopf', 'Halbiert Wirkzeit von Zaubern (Zufall: 10%)', 'Stab', 'Schnelligkeits'),
	(274, 'Stabhülle d. Hingabe', 'Lebenspunkte +45 (bei Verzauberung)', 'Stab', 'Hingabe'),
	(275, 'Stabhülle d. Ausdauer', 'Lebenspunkte +45 (während eine Haltung eingenommen wird)', 'Stab', 'Ausdauer'),
	(276, 'Stabhülle d. Wertschätzung', 'Lebenspunkte +60 (bei Verhexung)', 'Stab', 'Wertschätzung'),
	(277, 'Inschrift: "Auf die Erinnerung!"', 'Halbiert Fertigkeitswiederaufladung von Zaubern (Zufall: 10%)', 'Kampfwaffen', ''),
	(278, 'Inschrift: "Habt Vertrauen"', 'Energie +5 (bei Verzauberung)', 'Zauberwirker-Wegpunkte', ''),
	(279, 'Inschrift: "Sie kehren niemals wieder!"', 'Energie +7 (während Lebenspunkte weniger als 50% beträgt)', 'Zauberwirker-Wegpunkte', ''),
	(280, 'Inschrift: "Ich bin es leid"', 'Energie +7 (bei Verhexung)', 'Zauberwirker-Wegpunkte', ''),
	(281, 'Inschrift: "Zauderei ist keine Zier"', 'Halbiert Wirkzeit von Zaubern (Zufall: 10%)', 'Waffen', ''),
	(282, 'Inschrift: "Zu viel Information"', 'Schaden +15% (gg. verhexte Feinde)', 'Waffen', ''),
	(283, 'Inschrift: "Wink des Schicksals"', 'Schaden +15% (bei Verzauberung)', 'Waffen', ''),
	(284, 'Inschrift: "Ein gesunder Geist..."', 'Reduziert Benommenheit-Dauer bei Euch um 20% (Stapelbar)|Reduziert von dir erlittene und zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Fokus-Gegenstände oder Schilde', ''),
	(285, 'Inschrift: "Nur die Stärksten überleben!"', 'Reduziert Schwäche-Dauer bei Euch um 20% (Stapelbar)|Reduziert von dir erlittene und zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Fokus-Gegenstände oder Schilde', ''),
	(286, 'Inschrift: "Keine Angst vorm Sensenmann"', 'Schaden +20% (bei Verhexung)', 'Waffen', ''),
	(287, 'Inschrift: "Tanz mit dem Tod"', 'Schaden +15% (bei Haltung)', 'Waffen', ''),
	(288, 'Inschrift: "Körper über Geist"', 'Schaden +15%|Energie -5', 'Waffen', ''),
	(289, 'Inschrift: "Fühlt den Schmerz!"', 'Schaden +15%|Rüstung -10 (beim Angriff)', 'Waffen', ''),
	(290, 'Überlebende Befähigung', '%s Lebenspunkte +15 (bei Brustrüstung)|Lebenspunkte +10 (bei Beinrüstung)|Lebenspunkte +5 (bei anderer Rüstung)|||Lebenspunkte +15||Lebenspunkte +10||Lebenspunkte +5', 'Rüstung', 'Überlebende %s'),
	(291, 'Radianten-Befähigung', '%s Energie +3 (bei Brustrüstung)|Energie +2 (bei Beinrüstung)|Energie +1 (bei anderer Rüstung)|||Energie +3||Energie +2||Energie +1', 'Rüstung', 'Radianten'),
	(292, 'Entschlossenheits-Befähigung', 'Rüstung +10 (gg. körperlichen Schaden)', 'Rüstung', 'Entschlossenheits'),
	(293, 'Raufbold-Befähigung', 'Rüstung +10 (beim Angriff)', 'Rüstung', 'Raufbold'),
	(294, 'Segens-Befähigung', 'Rüstung +10 (unter Einfluss von Folgendem: Verzauberungen)', 'Rüstung', 'Segens'),
	(295, 'Herold-Befähigung', 'Rüstung +10 (beim Halten eines Gegenstandes)', 'Rüstung', 'Herold'),
	(296, 'Wachposten-Befähigung', 'Rüstung +10 (während eine Haltung eingenommen wird)', 'Rüstung', 'Wachposten'),
	(297, 'Hauptmann-[Assassinen]-Befähigung', 'Rüstung +10 (gg. körperlichen Schaden)|Rüstung +10 (gg. Stumpfschaden)', 'Assassinen-Rüstung', 'Hauptmann'),
	(298, 'Eindringlings-[Assassinen]-Befähigung', 'Rüstung +10 (gg. körperlichen Schaden)|Rüstung +10 (gg. Stichschaden)', 'Assassinen-Rüstung', 'Eindringlings'),
	(299, 'Saboteur-[Assassinen]-Befähigung', 'Rüstung +10 (gg. körperlichen Schaden)|Rüstung +10 (gg. Hiebschaden)', 'Assassinen-Rüstung', 'Saboteur'),
	(300, 'Nachtprischer-[Assassinen]-Befähigung', 'Rüstung +15 (beim Angriff)', 'Assassinen-Rüstung', 'Nachtpirscher'),
	(301, 'Virtuosen-[Mesmer]-Befähigung', 'Rüstung +15 (beim Aktivieren von Fertigkeiten)', 'Mesmer-Rüstung', 'Virtuosen'),
	(302, 'Blutfleck-[Nekromanten]-Befähigung', 'Reduziert die Wirkzeit von Zaubern, die Kadaver benutzen, um 25%. (Nicht stapelbar)', 'Nekromanten-Rüstung', 'Blutfleck'),
	(303, 'Folterer-[Nekromanten]-Befähigung', '%s Sakral-Schaden, den Ihr nehmt, wird um 6 erhöht (bei Brustrüstung)|Sakral-Schaden, den Ihr nehmt, wird um 4 erhöht (bei Beinrüstung)|Sakral-Schaden, den Ihr nehmt, wird um 2 erhöht (bei anderer Rüstung)|Rüstung +10|||Sakral-Schaden, den Ihr nehmt, wird um 6 erhöht|Rüstung +10||Sakral-Schaden, den Ihr nehmt, wird um 4 erhöht|Rüstung +10||Sakral-Schaden, den Ihr nehmt, wird um 2 erhöht|Rüstung +10', 'Nekromanten-Rüstung', 'Folterer'),
	(304, 'Klöppelspitzen-[Nekromanten]-Befähigung', 'Rüstung +15 (gg. Stichschaden)', 'Nekromanten-Rüstung', 'Klöppelspitzen'),
	(305, 'Dienermeister-[Nekromanten]-Befähigung', 'Rüstung +5 (beim Kontrollieren von 1 oder mehr Dienern)|Rüstung +5 (beim Kontrollieren von 3 oder mehr Dienern)|Rüstung +5 (beim Kontrollieren von 5 oder mehr Dienern)', 'Nekromanten-Rüstung', 'Dienermeister'),
	(306, 'Verderber-[Nekromanten]-Befähigung', 'Rüstung +20 (unter dem Einfluss von Folgendem: Verhexungen)', 'Nekromanten-Rüstung', 'Verderber'),
	(307, 'Hydromanten-[Elementarmagier]-Befähigung', 'Rüstung +10 (gg. Elementarschaden)|Rüstung +10 (gg. Kälteschaden)', 'Elementarmagier-Rüstung', 'Hydromanten'),
	(308, 'Geomanten-[Elementarmagier]-Befähigung', 'Rüstung +10 (gg. Elementarschaden)|Rüstung +10 (gg. Erdschaden)', 'Elementarmagier-Rüstung', 'Geomanten'),
	(309, 'Pyromanten-[Elementarmagier]-Befähigung', 'Rüstung +10 (gg. Elementarschaden)|Rüstung +10 (gg. Feuerschaden)', 'Elementarmagier-Rüstung', 'Pyromanten'),
	(310, 'Aeromanten-[Elementarmagier]-Befähigung', 'Rüstung +10 (gg. Elementarschaden)|Rüstung +10 (gg. Blitzschaden)', 'Elementarmagier-Rüstung', 'Aeromanten'),
	(311, 'Wanderer-[Mönchs]-Befähigung', 'Rüstung +10 (gg. Elementarschaden)', 'Mönchs-Rüstung', 'Wanderer'),
	(312, 'Jünger-[Mönchs]-Befähigung', 'Rüstung +15 (unter dem Einfluss von Folgendem: Zustände)', 'Mönchs-Rüstung', 'Jünger'),
	(313, 'Ritter-[Krieger]-Befähigung', 'Erlittener körperlicher Schaden -3', 'Krieger-Rüstung', 'Ritter'),
	(314, 'Leutnant-[Krieger]-Befähigung', 'Reduziert die Dauer von Verhexungen auf Euch um 20% und Schaden, den Ihr zufügt um 5%. (Nicht stapelbar)|Rüstung -20', 'Krieger-Rüstung', 'Leutnant'),
	(315, 'Steinfaust-[Krieger]-Befähigung', 'Erhöht die Dauer der Zeit, die ein Gegner außer Gefecht gesetzt wird, um 1 Sekunde. (Maximal: 3 Sekunden) (Nicht stapelbar)', 'Krieger-Rüstung', 'Steinfaust'),
	(316, 'Panzerschiff-[Krieger]-Befähigung', 'Rüstung +10 (gg. Elementarschaden)', 'Krieger-Rüstung', 'Panzerschiff'),
	(317, 'Wächter-[Krieger]-Fähigung', 'Rüstung +20 (Erfordert 13 Stärke, gg. Elementarschaden)', 'Krieger-Rüstung', 'Wächter'),
	(318, 'Permafrost-[Waldläufer]-Verfähigung', 'Rüstung +15 (gg. Kälteschaden)', 'Waldläufer-Rüstung', 'Permafrost'),
	(319, 'Scheiterhaufen-[Waldläufer]-Befähigung', 'Rüstung +15 (gg. Feuerschaden)', 'Waldläufer-Rüstung', 'Scheiterhaufen'),
	(320, 'Unwetter-[Waldläufer]-Befähigung', 'Rüstung +15 (gg. Blitzschaden)', 'Waldläufer-Rüstung', 'Unwetter'),
	(321, 'Späher-[Waldläufer]-Befähigung', 'Rüstung +10 (bei der Benutzung einer Vorbereitung)', 'Waldläufer-Rüstung', 'Späher'),
	(322, 'Schamanen-[Ritualisten]-Befähigung', 'Rüstung +5 (beim Kontrollieren von 1 oder mehr Geistern)|Rüstung +5 (beim Kontrollieren von 2 oder mehr Geistern)|Rüstung +5 (beim Kontrollieren von 3 oder mehr Geistern)', 'Ritualisten-Rüstung', 'Schamanen'),
	(323, 'Geisterschmiede-[Ritualisten]-Befähigung', 'Rüstung +15 (unter dem Einfluss von Folgendem: Waffenzauber)', 'Ritualisten-Rüstung', 'Geisterschmiede'),
	(324, 'Mystiker-[Ritualisten]-Befähigung', 'Rüstung +15 (beim Aktivieren von Fertigkeiten)', 'Ritualisten-Rüstung', 'Mystiker'),
	(325, 'Inschrift: "Der Glaube ist mein Schild"', 'Rüstung +5 (bei Verzauberung)', 'Fokus-Gegenstände', ''),
	(326, 'Inschrift: "Lebt den Tag"', 'Energie +15|Regeneration von Energiepunkten -1', 'Fokus-Gegenstände', ''),
	(327, 'Inschrift: "Auf die Gelassenheit"', 'Halbiert Fertigkeitswiederaufladung von Zaubern (Zufall: 10%)', 'Fokus-Gegenstände', ''),
	(328, 'Inschrift: "Vergesst mein nicht!"', 'Halbiert Fertigkeitswiederaufladung von Zaubern desselben Attributes des Gegenstandes (Zufall: 20%)', 'Fokus-Gegenstände', ''),
	(329, 'Inschrift: "Ich habe die Kraft!"', 'Energie +5', 'Kampfwaffen', ''),
	(330, 'Inschrift: "Glück im Spiel..."', 'Erlittener körperlicher Schaden -5 (Zufall: 20%)', 'Fokus-Gegenstände oder Schilde', ''),
	(331, 'Inschrift: "Vertrauen ist gut"', 'Erlittener körperlicher Schaden -2 (bei Verzauberung)', 'Fokus-Gegenstände oder Schilde', ''),
	(332, 'Inschrift: "Nichts zu befürchten"', 'Erlittener körperlicher Schaden -3 (bei Verhexung)', 'Fokus-Gegenstände oder Schilde', ''),
	(333, 'Inschrift: "Rennt um Euer Leben!"', 'Erlittener körperlicher Schaden -2 (bei Haltung)', 'Fokus-Gegenstände oder Schilde', ''),
	(334, 'Inschrift: "Herr in meinem Haus"', 'Gegenstandsattribut +1 (Zufall: 20%)', 'Fokus-Gegenstände oder Schilde', ''),
	(335, 'Inschrift: "Gut gewirkt ist halb gewonnen"', 'Halbiert Wirkzeit von Zaubern desselben Attributes des Gegenstandes (Zufall: 20%)', 'Zauberwirker-Wegpunkte', ''),
	(336, 'Inschrift: "Nutzt den Tag"', 'Energie +15|Regeneration von Energiepunkten -1', 'Zauberwirker-Wegpunkte', ''),
	(337, 'Inschrift: "Gesund und Munter"', 'Energie +5 (während Lebenspunkte mehr als 50% beträgt)', 'Zauberwirker-Wegpunkte', ''),
	(338, 'Inschrift: "Stärke und Ehre"', 'Schaden +15% (während Lebenspunkte mehr als 50% beträgt)', 'Waffen', ''),
	(339, 'Inschrift: "Die Rache ist mein"', 'Schaden +20% (während Lebenspunkte weniger als 50% beträgt)', 'Waffen', ''),
	(340, 'Fokus-Kern d. Tapferkeit', 'Lebenspunkte +30', 'Fokus', 'Tapferkeit'),
	(341, 'Fokus-Kern d. Hingabe', 'Lebenspunkte +45 (bei Verzauberung)', 'Fokus', 'Hingabe'),
	(342, 'Fokus-Kern d. Eile', 'Halbiert Wirkzeit von Zaubern (Zufall: 10%)', 'Fokus', 'Eile'),
	(343, 'Fokus-Kern d. Begabung', 'Halbiert Wirkzeit von Zaubern desselben Attributs des Gegenstandes (Zufall: 20%)', 'Fokus', 'Begabung'),
	(344, 'Zauberstab-Hülle d. Beschleunigung', 'Halbiert Fertigkeitswiederaufladung von Zaubern (Zufall: 10%)', 'Zauberstab', 'Beschleunigung'),
	(345, 'Zauberstab-Hülle d. Erinnerung', 'Halbiert Fertigkeitswiederaufladung von Zaubern desselben Attributs des Gegenstandes (Zufall: 20%)', 'Zauberstab', 'Erinnerung'),
	(346, 'Schildgriff d. Tapferkeit', 'Lebenspunkte +30', 'Schild', 'Tapferkeit'),
	(347, 'Schildgriff d. Hingabe', 'Lebenspunkte +45 (bei Verzauberung)', 'Schild', 'Hingabe'),
	(348, 'Schildgriff d. Ausdauer', 'Lebenspunkte +45 (während eine Haltung eingenommen wird)', 'Schild', 'Ausdauer'),
	(349, 'Schildgriff d. Wertschätzung', 'Lebenspunkte +60 (bei Verhexung)', 'Schild', 'Wertschätzung'),
	(350, 'Experten-Stabkopf', 'Halbiert Wirkzeit von Zaubern desselben Attributes des Gegenstandes (Zufall: 20%)', 'Stab', 'Experten'),
	(351, 'Stabhülle d. Beherrschung', 'Gegenstandsattribut +1 (20%ige Chance bei Verwendung von Fertigkeiten)', 'Stab', 'Beherrschung'),
	(352, 'Rune d. Einstimmung', 'Energie +2', 'Rüstung', 'Einstimmung'),
	(353, 'Rune d. Lebenskraft', 'Lebenspunkte +10', 'Rüstung', 'Lebenskraft'),
	(354, 'Rune d. Gesundung', 'Reduziert von Euch erlittene und zugefügte Blutung-Dauer um 20% (Nicht stapelbar)|Reduziert Benommenheit-Dauer bei Euch um 20% (Nicht stapelbar)|Reduziert Tiefe Wunde-Dauer bei Euch um 20% (Nicht stapelbar)', 'Rüstung', 'Gesundung'),
	(355, 'Rune d. Wiederherstellung', 'Reduziert von Euch erlittene und zugefügte Blutung-Dauer um 20% (Nicht stapelbar)|Reduziert Verkrüppelung-Dauer bei Euch um 20% (Nicht stapelbar)', 'Rüstung', 'Wiederherstellung'),
	(356, 'Rune d. Klarheit', 'Reduziert von Euch erlittene und zugefügte Blutung-Dauer um 20% (Nicht stapelbar)|Reduziert Blindheit-Dauer bei Euch um 20% (Nicht stapelbar)|Reduziert Schwäche-Dauer bei Euch um 20% (Nicht stapelbar)', 'Rüstung', 'Klarheit'),
	(357, 'Rune d. Reinheit', 'Reduziert von Euch erlittene und zugefügte Blutung-Dauer um 20% (Nicht stapelbar)|Reduziert Krankheit-Dauer bei Euch um 20% (Nicht stapelbar)|Reduziert Gift-Dauer bei Euch um 20% (Nicht stapelbar)', 'Rüstung', 'Reinheit'),
	(358, 'Feuerwerker-[Mesmer]-Befähigung', 'Rüstung +3 (für jedes ausgerüstete Siegel)', 'Mesmer-Rüstung', 'Feuerwerker'),
	(359, 'Wunder-[Mesmer]-Befähigung', 'Rüstung +5 (beim Wiederaufladen von 1 oder mehr Fertigkeiten)|Rüstung +5 (beim Wiederaufladen von 3 oder mehr Fertigkeiten)|Rüstung +5 (beim Wiederaufladen von 5 oder mehr Fertigkeiten)', 'Mesmer-Rüstung', 'Wunder'),
	(360, 'Leichenbestatter-[Nekromanten]-Befähigung', 'Rüstung +5 (während Lebenspunkte weniger als 80% beträgt)|Rüstung +5 (während Lebenspunkte weniger als 60% beträgt)|Rüstung +5 (während Lebenspunkte weniger als 40% beträgt)|Rüstung +5 (während Lebenspunkte weniger als 20% beträgt)', 'Nekromanten-Rüstung', 'Leichenbestatter'),
	(361, 'Spektral-[Elementarmagier]-Befähigung', 'Rüstung +5 (Erfordert 9 Luftmagie)|Rüstung +5 (Erfordert 9 Erdmagie)|Rüstung +5 (Erfordert 9 Feuermagie)|Rüstung +5 (Erfordert 9 Wassermagie)', 'Elementarmagier-Rüstung', 'Spektral'),
	(362, 'Einsiedler-[Mönchs]-Befähigung', 'Rüstung +5 (beim Wiederaufladen von 1 oder mehr Fertigkeiten)|Rüstung +5 (beim Wiederaufladen von 3 oder mehr Fertigkeiten)|Rüstung +5 (beim Wiederaufladen von 5 oder mehr Fertigkeiten)', 'Mönchs-Rüstung', 'Einsiedler'),
	(363, 'Erdbindung-[Waldläufer]-Befähigung', 'Rüstung +15 (gg. Erdschaden)', 'Waldläufer-Rüstung', 'Erdbindung'),
	(364, 'Tierbändiger-[Waldläufer]-Befähigung', 'Rüstung +10 (während Euer Tier am Leben ist)', 'Waldläufer-Rüstung', 'Tierbändiger'),
	(365, 'Windläufer-[Derwisch]-Befähigung', 'Rüstung +5 (unter dem Einfluss von 1 oder mehr von Folgendem: Verzauberung)|Rüstung +5 (unter dem Einfluss von 2 oder mehr von Folgendem: Verzauberungen)|Rüstung +5 (unter dem Einfluss von 3 oder mehr von Folgendem: Verzauberungen)|Rüstung +5 (unter dem Einfluss von 4 oder mehr von Folgendem: Verzauberungen)', 'Derwisch-Rüstung', 'Windläufer'),
	(366, 'Verlassenen-[Derwisch]-Befähigung', 'Rüstung +10 (wenn nicht unter dem Einfluss von Folgendem: Verzauberungen)', 'Derwisch-Rüstung', 'Verlassenen'),
	(367, 'Zenturio-[Paragon]-Befähigung', 'Rüstung +10 (unter dem Einfluss eines Schreis, Echos oder Anfeuerungsrufes)', 'Paragon-Rüstung', 'Zenturio'),
	(368, 'Inschrift: "Was ich nicht weiß..."', 'Rüstung +5|Energie -5', 'Fokus-Gegenstände', ''),
	(369, 'Inschrift: "Das Leben tut weh"', 'Rüstung +5|Lebenspunkte -20', 'Fokus-Gegenstände', ''),
	(370, 'Inschrift: "Ein Mann für alle Jahreszeiten"', 'Rüstung +5 (gg. Elementarschaden)', 'Fokus-Gegenstände', ''),
	(371, 'Inschrift: "Hart wie Stahl"', 'Rüstung +5 (gg. körperlichen Schaden)', 'Fokus-Gegenstände', ''),
	(372, 'Inschrift: "Macht gibt Recht"', 'Rüstung +5 (beim Angriff)', 'Fokus-Gegenstände', ''),
	(373, 'Inschrift: "Wissen ist die halbe Miete"', 'Rüstung +5 (beim Wirken)', 'Fokus-Gegenstände', ''),
	(374, 'Inschrift: "Am Boden aber nicht zerstört"', 'Rüstung +10 (während Lebenspunkte weniger als 50% beträgt)', 'Fokus-Gegenstände', ''),
	(375, 'Inschrift: "Gelobt sei der König"', 'Rüstung +5 (während Lebenspunkte mehr als 50% beträgt)', 'Fokus-Gegenstände', ''),
	(376, 'Inschrift: "Der Gerechte braucht sich nicht zu fürchten."', 'Rüstung +10 (bei Verhexung)', 'Fokus-Gegenstände', ''),
	(377, 'Inschrift: "Nicht das Gesicht!"', 'Rüstung +10 (gg. Stumpfschaden)', 'Fokus-Gegenstände oder Schilde', ''),
	(378, 'Inschrift: "Grashalm im Wind"', 'Rüstung +10 (gg. Kälteschaden)', 'Fokus-Gegenstände oder Schilde', ''),
	(379, 'Inschrift: "Marmor, Stein und Erde bricht"', 'Rüstung +10 (gg. Erdschaden)', 'Fokus-Gegenstände oder Schilde', ''),
	(380, 'Inschrift: "Geblitzt wird nicht!"', 'Rüstung +10 (gg. Blitzschaden)', 'Fokus-Gegenstände oder Schilde', ''),
	(381, 'Inschrift: "Geborgenheit im Feuer"', 'Rüstung +10 (gg. Feuerschaden)', 'Fokus-Gegenstände oder Schilde', ''),
	(382, 'Inschrift: "Durch dick und dünn"', 'Rüstung +10 (gg. Stichschaden)', 'Fokus-Gegenstände oder Schilde', ''),
	(383, 'Inschrift: "Hieb- und stahlfest"', 'Rüstung +10 (gg. Hiebschaden)', 'Fokus-Gegenstände oder Schilde', ''),
	(384, 'Inschrift: "Die Furcht schneidet tiefer"', 'Reduziert Blutung-Dauer bei Euch um 20% (Stapelbar)|Reduziert von dir erlittene und zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Fokus-Gegenstände oder Schilde', '');
INSERT INTO `gw1_modifierdesc_de` (`id`, `name`, `desc`, `base`, `ext`) VALUES
	(385, 'Inschrift: "Klar wie Morgentau"', 'Reduziert Blindheit-Dauer bei Euch um 20% (Stapelbar)|Reduziert von dir erlittene und zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Fokus-Gegenstände oder Schilde', ''),
	(386, 'Inschrift: "Schnell wie der Wind"', 'Reduziert Verkrüppelung-Dauer bei Euch um 20% (Stapelbar)|Reduziert von dir erlittene und zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Fokus-Gegenstände oder Schilde', ''),
	(387, 'Inschrift: "Hart im Nehmen"', 'Reduziert Tiefe Wunde-Dauer bei Euch um 20% (Stapelbar)|Reduziert von dir erlittene und zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Fokus-Gegenstände oder Schilde', ''),
	(388, 'Inschrift: "Gute Besserung!"', 'Reduziert Krankheit-Dauer bei Euch um 20% (Stapelbar)|Reduziert von dir erlittene und zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Fokus-Gegenstände oder Schilde', ''),
	(389, 'Inschrift: "Mein Herz ist rein"', 'Reduziert Gift-Dauer bei Euch um 20% (Stapelbar)|Reduziert von dir erlittene und zugefügte Blutung-Dauer um eine Sekunde (Stapelbar)', 'Fokus-Gegenstände oder Schilde', '');
