CREATE TABLE IF NOT EXISTS `gw1_itemdesc_en` (
	`id`        SMALLINT(3) UNSIGNED NOT NULL,
	`name`      TINYTEXT             NOT NULL,
	`wiki`      TINYTEXT             NOT NULL,
	`type`      ENUM('Axe', 'Legs Armor', 'Bow', 'Chest Armor', 'Daggers', 'Focus Item', 'Footwear', 'Hammer', 'Hands Armor', 'Headgear', 'Shield', 'Sword', 'Scythe', 'Spear', 'Staff', 'Wand') NOT NULL,
	`base_type` ENUM('-', 'Lightning Dmg', 'Chaos Dmg', 'Dark Dmg', 'Energy', 'Earth Dmg', 'Fire Dmg', 'Slashing Dmg', 'Cold Dmg', 'Armor', 'Holy Dmg', 'Piercing Dmg', 'Blunt Dmg', 'Water Dmg') NOT NULL DEFAULT '-',
	PRIMARY KEY (`id`)
)
	ENGINE = InnoDB
	DEFAULT CHARSET = utf8mb4
	COLLATE = utf8mb4_bin;

INSERT INTO `gw1_itemdesc_en` (`id`, `name`, `wiki`, `type`, `base_type`) VALUES
	(1, 'PvP Enchanter Footwear', 'Mesmer Enchanter armor', 'Footwear', '-'),
	(2, 'PvP Theatrical Footwear', 'Mesmer Performer armor', 'Footwear', '-'),
	(3, 'PvP Rogue Footwear', 'Mesmer Rogue armor', 'Footwear', '-'),
	(4, 'PvP Wretched Boots', 'Necromancer Cabal armor', 'Footwear', '-'),
	(5, 'PvP Banished Boots', 'Necromancer Profane armor', 'Footwear', '-'),
	(6, 'PvP Foot Scar Pattern', 'Necromancer Fanatic armor', 'Footwear', '-'),
	(8, 'PvP Stormcloud Shoes', 'Elementalist Stormforged armor', 'Footwear', '-'),
	(9, 'PvP Granite Shoes', 'Elementalist Stoneforged armor', 'Footwear', '-'),
	(10, 'PvP Magma Shoes', 'Elementalist Flameforged armor', 'Footwear', '-'),
	(11, 'PvP Frozen Shoes', 'Elementalist Iceforged armor', 'Footwear', '-'),
	(12, 'PvP Consecrated Sandals', 'Monk Woven armor', 'Footwear', '-'),
	(13, 'PvP Ascetic Foot Design', 'Monk Dragon armor', 'Footwear', '-'),
	(14, 'PvP Militant Sandals', 'Monk Censor armor', 'Footwear', '-'),
	(15, 'PvP Dragon Boots', 'Warrior Wyvern armor', 'Footwear', '-'),
	(16, 'PvP Gladiator Boots', 'Warrior Gladiator armor', 'Footwear', '-'),
	(17, 'PvP Plated Boots', 'Warrior Templar armor', 'Footwear', '-'),
	(18, 'PvP Druidic Boots', 'Ranger Druid armor', 'Footwear', '-'),
	(19, 'PvP Fur-Lined Boots', 'Ranger Fur-Lined armor', 'Footwear', '-'),
	(20, 'PvP Studded Leather Boots', 'Ranger Studded Leather armor', 'Footwear', '-'),
	(21, 'PvP Drakescale Boots', 'Ranger Drakescale armor', 'Footwear', '-'),
	(22, 'PvP Enchanter Attire', 'Mesmer Enchanter armor', 'Chest Armor', '-'),
	(23, 'PvP Theatrical Attire', 'Mesmer Performer armor', 'Chest Armor', '-'),
	(24, 'PvP Rogue Attire', 'Mesmer Rogue armor', 'Chest Armor', '-'),
	(25, 'PvP Wretched Tunic', 'Necromancer Cabal armor', 'Chest Armor', '-'),
	(26, 'PvP Banished Tunic', 'Necromancer Profane armor', 'Chest Armor', '-'),
	(27, 'PvP Chest Scar Pattern', 'Necromancer Fanatic armor', 'Chest Armor', '-'),
	(28, 'PvP Stormcloud Robes', 'Elementalist Stormforged armor', 'Chest Armor', '-'),
	(29, 'PvP Granite Robes', 'Elementalist Stoneforged armor', 'Chest Armor', '-'),
	(30, 'PvP Magma Robes', 'Elementalist Flameforged armor', 'Chest Armor', '-'),
	(31, 'PvP Frozen Robes', 'Elementalist Iceforged armor', 'Chest Armor', '-'),
	(32, 'PvP Consecrated Vestments', 'Monk Woven armor', 'Chest Armor', '-'),
	(33, 'PvP Ascetic Chest Design', 'Monk Dragon armor', 'Chest Armor', '-'),
	(34, 'PvP Militant Vestments', 'Monk Censor armor', 'Chest Armor', '-'),
	(35, 'PvP Dragon Cuirass', 'Warrior Wyvern armor', 'Chest Armor', '-'),
	(36, 'PvP Gladiator Cuirass', 'Warrior Gladiator armor', 'Chest Armor', '-'),
	(37, 'PvP Plated Cuirass', 'Warrior Templar armor', 'Chest Armor', '-'),
	(38, 'PvP Druidic Vest', 'Ranger Druid armor', 'Chest Armor', '-'),
	(39, 'PvP Fur-Lined Vest', 'Ranger Fur-Lined armor', 'Chest Armor', '-'),
	(40, 'PvP Studded Leather Vest', 'Ranger Studded Leather armor', 'Chest Armor', '-'),
	(41, 'PvP Drakescale Vest', 'Ranger Drakescale armor', 'Chest Armor', '-'),
	(42, 'PvP Enchanter Gloves', 'Mesmer Enchanter armor', 'Hands Armor', '-'),
	(43, 'PvP Theatrical Gloves', 'Mesmer Performer armor', 'Hands Armor', '-'),
	(44, 'PvP Rogue Gloves', 'Mesmer Rogue armor', 'Hands Armor', '-'),
	(45, 'PvP Wretched Gloves', 'Necromancer Cabal armor', 'Hands Armor', '-'),
	(46, 'PvP Banished Gloves', 'Necromancer Profane armor', 'Hands Armor', '-'),
	(47, 'PvP Arm Scar Pattern', 'Necromancer Fanatic armor', 'Hands Armor', '-'),
	(48, 'PvP Stormcloud Gloves', 'Elementalist Stormforged armor', 'Hands Armor', '-'),
	(49, 'PvP Granite Gloves', 'Elementalist Stoneforged armor', 'Hands Armor', '-'),
	(50, 'PvP Magma Gloves', 'Elementalist Flameforged armor', 'Hands Armor', '-'),
	(51, 'PvP Frozen Gloves', 'Elementalist Iceforged armor', 'Hands Armor', '-'),
	(52, 'PvP Consecrated Handwraps', 'Monk Woven armor', 'Hands Armor', '-'),
	(53, 'PvP Ascetic Arm Design', 'Monk Dragon armor', 'Hands Armor', '-'),
	(54, 'PvP Militant Handwraps', 'Monk Censor armor', 'Hands Armor', '-'),
	(55, 'PvP Dragon Gauntlets', 'Warrior Wyvern armor', 'Hands Armor', '-'),
	(56, 'PvP Gladiator Gauntlets', 'Warrior Gladiator armor', 'Hands Armor', '-'),
	(57, 'PvP Plated Gauntlets', 'Warrior Templar armor', 'Hands Armor', '-'),
	(59, 'PvP Druidic Gloves', 'Ranger Druid armor', 'Hands Armor', '-'),
	(60, 'PvP Fur-Lined Gloves', 'Ranger Fur-Lined armor', 'Hands Armor', '-'),
	(61, 'PvP Studded Leather Gloves', 'Ranger Studded Leather armor', 'Hands Armor', '-'),
	(62, 'PvP Drakescale Gloves', 'Ranger Drakescale armor', 'Hands Armor', '-'),
	(63, 'PvP Imposing Mask', 'Mesmer headgear', 'Headgear', '-'),
	(64, 'PvP Sleek Mask', 'Mesmer headgear', 'Headgear', '-'),
	(65, 'PvP Costume Mask', 'Mesmer headgear', 'Headgear', '-'),
	(66, 'PvP Animal Mask', 'Mesmer headgear', 'Headgear', '-'),
	(67, 'PvP Ragged Scar Pattern', 'Necromancer headgear', 'Headgear', '-'),
	(68, 'PvP Wicked Scar Pattern', 'Necromancer headgear', 'Headgear', '-'),
	(69, 'PvP Vile Scar Pattern', 'Necromancer headgear', 'Headgear', '-'),
	(70, 'PvP Devilish Scar Pattern', 'Necromancer headgear', 'Headgear', '-'),
	(71, 'PvP Storm\'s Eye', 'Elementalist headgear', 'Headgear', '-'),
	(72, 'PvP Stone\'s Eye', 'Elementalist headgear', 'Headgear', '-'),
	(73, 'PvP All-Seeing Eye', 'Elementalist headgear', 'Headgear', '-'),
	(74, 'PvP Flame\'s Eye', 'Elementalist headgear', 'Headgear', '-'),
	(75, 'PvP Glacier\'s Eye', 'Elementalist headgear', 'Headgear', '-'),
	(76, 'PvP Divine Scalp Design', 'Monk headgear', 'Headgear', '-'),
	(77, 'PvP Healer Scalp Design', 'Monk headgear', 'Headgear', '-'),
	(78, 'PvP Protector Scalp Design', 'Monk headgear', 'Headgear', '-'),
	(79, 'PvP Smiting Scalp Design', 'Monk headgear', 'Headgear', '-'),
	(80, 'PvP Executioner Helm', 'Warrior Gladiator armor', 'Headgear', '-'),
	(81, 'PvP Dwarven Helm', 'Warrior Gladiator armor', 'Headgear', '-'),
	(83, 'PvP Duelist Helm', 'Warrior Gladiator armor', 'Headgear', '-'),
	(84, 'PvP Brute Helm', 'Warrior Gladiator armor', 'Headgear', '-'),
	(85, 'PvP Gladiator Helm', 'Warrior Gladiator armor', 'Headgear', '-'),
	(86, 'PvP Tamer Mask', 'Ranger masks', 'Headgear', '-'),
	(87, 'PvP Archer Mask', 'Ranger masks', 'Headgear', '-'),
	(88, 'PvP Hunter Mask', 'Ranger masks', 'Headgear', '-'),
	(89, 'PvP Traveler Mask', 'Ranger masks', 'Headgear', '-'),
	(90, 'PvP Enchanter Hose', 'Mesmer Enchanter armor', 'Legs Armor', '-'),
	(91, 'PvP Theatrical Hose', 'Mesmer Performer armor', 'Legs Armor', '-'),
	(92, 'PvP Rogue Hose', 'Mesmer Rogue armor', 'Legs Armor', '-'),
	(93, 'PvP Wretched Leggings', 'Necromancer Cabal armor', 'Legs Armor', '-'),
	(94, 'PvP Banished Leggings', 'Necromancer Profane armor', 'Legs Armor', '-'),
	(95, 'PvP Leg Scar Pattern', 'Necromancer Fanatic armor', 'Legs Armor', '-'),
	(96, 'PvP Stormcloud Leggings', 'Elementalist Stormforged armor', 'Legs Armor', '-'),
	(97, 'PvP Granite Leggings', 'Elementalist Stoneforged armor', 'Legs Armor', '-'),
	(98, 'PvP Magma Leggings', 'Elementalist Flameforged armor', 'Legs Armor', '-'),
	(99, 'PvP Frozen Leggings', 'Elementalist Iceforged armor', 'Legs Armor', '-'),
	(100, 'PvP Consecrated Pants', 'Monk Woven armor', 'Legs Armor', '-'),
	(101, 'PvP Ascetic Leg Design', 'Monk Dragon armor', 'Legs Armor', '-'),
	(102, 'PvP Militant Pants', 'Monk Censor armor', 'Legs Armor', '-'),
	(103, 'PvP Dragon Leggings', 'Warrior Wyvern armor', 'Legs Armor', '-'),
	(104, 'PvP Gladiator Leggings', 'Warrior Gladiator armor', 'Legs Armor', '-'),
	(105, 'PvP Plated Leggings', 'Warrior Templar armor', 'Legs Armor', '-'),
	(106, 'PvP Druidic Leggings', 'Ranger Druid armor', 'Legs Armor', '-'),
	(107, 'PvP Fur-Lined Leggings', 'Ranger Fur-Lined armor', 'Legs Armor', '-'),
	(108, 'PvP Studded Leather Leggings', 'Ranger Studded Leather armor', 'Legs Armor', '-'),
	(109, 'PvP Drakescale Leggings', 'Ranger Drakescale armor', 'Legs Armor', '-'),
	(110, 'PvP Axe', 'War Axe', 'Axe', 'Slashing Dmg'),
	(111, 'PvP Flatbow', 'Feathered Flatbow', 'Bow', 'Piercing Dmg'),
	(112, 'PvP Hornbow', 'Stoneshard Hornbow', 'Bow', 'Piercing Dmg'),
	(113, 'PvP Longbow', 'Wooden Longbow', 'Bow', 'Piercing Dmg'),
	(114, 'PvP Shortbow', 'Shortbow', 'Bow', 'Piercing Dmg'),
	(115, 'PvP Recurve Bow', 'Composite Bow', 'Bow', 'Piercing Dmg'),
	(116, 'PvP Inscribed Chakram', 'Inscribed Chakram', 'Focus Item', 'Energy'),
	(117, 'PvP Glided Artifact', 'Gilded Artifact', 'Focus Item', 'Energy'),
	(118, 'PvP Jeweled Chakram', 'Jeweled Chakram', 'Focus Item', 'Energy'),
	(119, 'PvP Jeweled Chalice', 'Jeweled Chalice', 'Focus Item', 'Energy'),
	(120, 'PvP Idol', 'Idol', 'Focus Item', 'Energy'),
	(121, 'PvP Accursed Icon', 'Accursed Icon', 'Focus Item', 'Energy'),
	(122, 'PvP Grim Cesta', 'Grim Cesta', 'Focus Item', 'Energy'),
	(123, 'PvP Bone Idol', 'Bone Idol', 'Focus Item', 'Energy'),
	(124, 'PvP Storm Artifact', 'Storm Artifact', 'Focus Item', 'Energy'),
	(125, 'PvP Earth Scroll', 'Earth Scroll', 'Focus Item', 'Energy'),
	(126, 'PvP Golden Chalice', 'Golden Chalice', 'Focus Item', 'Energy'),
	(127, 'PvP Flame Artifact', 'Flame Artifact', 'Focus Item', 'Energy'),
	(128, 'PvP Frost Artifact', 'Frost Artifact', 'Focus Item', 'Energy'),
	(129, 'PvP Divine Symbol', 'Divine Symbol', 'Focus Item', 'Energy'),
	(130, 'PvP Healing Ankh', 'Healing Ankh', 'Focus Item', 'Energy'),
	(131, 'PvP Protective Icon', 'Protective Icon', 'Focus Item', 'Energy'),
	(132, 'PvP Hallowed Idol', 'Hallowed Idol', 'Focus Item', 'Energy'),
	(133, 'PvP Hammer', 'Magmas Arm', 'Hammer', 'Blunt Dmg'),
	(134, 'PvP Cane', 'Cane', 'Wand', 'Chaos Dmg'),
	(135, 'PvP Crystal Wand', 'Crystal Wand', 'Wand', 'Chaos Dmg'),
	(136, 'PvP Truncheon', 'Truncheon', 'Wand', 'Dark Dmg'),
	(137, 'PvP Deathly Cesta', 'Bone Spiral Rod', 'Wand', 'Cold Dmg'),
	(138, 'PvP Accursed Rod', 'Wailing Wand', 'Wand', 'Cold Dmg'),
	(139, 'PvP Air Wand', 'Air Wand', 'Wand', 'Lightning Dmg'),
	(140, 'PvP Earth Wand', 'Earth Wand', 'Wand', 'Earth Dmg'),
	(141, 'PvP Fire Wand', 'Fire Wand', 'Wand', 'Fire Dmg'),
	(142, 'PvP Water Wand', 'Water Wand', 'Wand', 'Water Dmg'),
	(143, 'PvP Holy Rod', 'Holy Rod', 'Wand', 'Fire Dmg'),
	(144, 'PvP Smiting Rod', 'Smiting Rod', 'Wand', 'Holy Dmg'),
	(145, 'PvP Strength Shield', 'Tower Shield', 'Shield', 'Armor'),
	(146, 'PvP Tactics Shield', 'Tall Shield', 'Shield', 'Armor'),
	(147, 'PvP Inscribed Staff', 'Inscribed Staff', 'Staff', 'Chaos Dmg'),
	(148, 'PvP Jeweled Staff', 'Jeweled Staff', 'Staff', 'Chaos Dmg'),
	(149, 'PvP Blood Staff', 'Evil Eye Staff', 'Staff', 'Dark Dmg'),
	(150, 'PvP Dead Staff', 'Bone Staff', 'Staff', 'Cold Dmg'),
	(151, 'PvP Accursed Staff', 'Accursed Staff', 'Staff', 'Cold Dmg'),
	(152, 'PvP Air Staff', 'Air Staff', 'Staff', 'Lightning Dmg'),
	(153, 'PvP Earth Staff', 'Earth Staff', 'Staff', 'Earth Dmg'),
	(154, 'PvP Fire Staff', 'Fire Staff', 'Staff', 'Fire Dmg'),
	(155, 'PvP Water Staff', 'Water Staff', 'Staff', 'Cold Dmg'),
	(156, 'PvP Holy Staff', 'Holy Staff', 'Staff', 'Fire Dmg'),
	(157, 'PvP Smiting Staff', 'Smiting Staff', 'Staff', 'Holy Dmg'),
	(158, 'PvP Sword', 'Short Sword', 'Sword', 'Slashing Dmg'),
	(159, 'PvP Shing Jea Shoes', 'Assassin Shing Jea armor', 'Footwear', '-'),
	(160, 'PvP Shing Jea Guise', 'Assassin Shing Jea armor', 'Chest Armor', '-'),
	(161, 'PvP Shing Jea Gloves', 'Assassin Shing Jea armor', 'Hands Armor', '-'),
	(162, 'PvP Shing Jea Leggings', 'Assassin Shing Jea armor', 'Legs Armor', '-'),
	(163, 'PvP Seitung Shoes', 'Assassin Seitung armor', 'Footwear', '-'),
	(164, 'PvP Seitung Guise', 'Assassin Seitung armor', 'Chest Armor', '-'),
	(165, 'PvP Seitung Gloves', 'Assassin Seitung armor', 'Hands Armor', '-'),
	(166, 'PvP Seitung Leggings', 'Assassin Seitung armor', 'Legs Armor', '-'),
	(167, 'PvP Imperial Shoes', 'Assassin Imperial armor', 'Footwear', '-'),
	(168, 'PvP Imperial Guise', 'Assassin Imperial armor', 'Chest Armor', '-'),
	(169, 'PvP Imperial Gloves', 'Assassin Imperial armor', 'Hands Armor', '-'),
	(170, 'PvP Imperial Leggings', 'Assassin Imperial armor', 'Legs Armor', '-'),
	(171, 'PvP Canthan Shoes', 'Assassin Canthan armor', 'Footwear', '-'),
	(172, 'PvP Canthan Guise', 'Assassin Canthan armor', 'Chest Armor', '-'),
	(173, 'PvP Canthan Gloves', 'Assassin Canthan armor', 'Hands Armor', '-'),
	(174, 'PvP Canthan Leggings', 'Assassin Canthan armor', 'Legs Armor', '-'),
	(175, 'PvP Exotic Shoes', 'Assassin Exotic armor', 'Footwear', '-'),
	(176, 'PvP Exotic Guise', 'Assassin Exotic armor', 'Chest Armor', '-'),
	(177, 'PvP Exotic Gloves', 'Assassin Exotic armor', 'Hands Armor', '-'),
	(178, 'PvP Exotic Leggings', 'Assassin Exotic armor', 'Legs Armor', '-'),
	(179, 'PvP Canthan Footwear', 'Mesmer Canthan armor', 'Footwear', '-'),
	(180, 'PvP Canthan Attire', 'Mesmer Canthan armor', 'Chest Armor', '-'),
	(181, 'PvP Canthan Gloves', 'Mesmer Canthan armor', 'Hands Armor', '-'),
	(182, 'PvP Canthan Hose', 'Mesmer Canthan armor', 'Legs Armor', '-'),
	(183, 'PvP Krytan Footwear', 'Mesmer Krytan armor', 'Footwear', '-'),
	(184, 'PvP Krytan Attire', 'Mesmer Krytan armor', 'Chest Armor', '-'),
	(185, 'PvP Krytan Gloves', 'Mesmer Krytan armor', 'Hands Armor', '-'),
	(186, 'PvP Krytan Hose', 'Mesmer Krytan armor', 'Legs Armor', '-'),
	(187, 'PvP Shing Jea Footwear', 'Mesmer Shing Jea armor', 'Footwear', '-'),
	(188, 'PvP Shing Jea Attire', 'Mesmer Shing Jea armor', 'Chest Armor', '-'),
	(189, 'PvP Shing Jea Gloves', 'Mesmer Shing Jea armor', 'Hands Armor', '-'),
	(190, 'PvP Shing Jea Hose', 'Mesmer Shing Jea armor', 'Legs Armor', '-'),
	(191, 'PvP Krytan Boots', 'Necromancer Krytan armor', 'Footwear', '-'),
	(192, 'PvP Krytan Tunic', 'Necromancer Krytan armor', 'Chest Armor', '-'),
	(193, 'PvP Krytan Gloves', 'Necromancer Krytan armor', 'Hands Armor', '-'),
	(194, 'PvP Krytan Leggings', 'Necromancer Krytan armor', 'Legs Armor', '-'),
	(195, 'PvP Canthan Boots', 'Necromancer Canthan armor', 'Footwear', '-'),
	(196, 'PvP Canthan Tunic', 'Necromancer Canthan armor', 'Chest Armor', '-'),
	(197, 'PvP Canthan Gloves', 'Necromancer Canthan armor', 'Hands Armor', '-'),
	(198, 'PvP Canthan Leggings', 'Necromancer Canthan armor', 'Legs Armor', '-'),
	(199, 'PvP Shing Jea Boots', 'Necromancer Shing Jea armor', 'Footwear', '-'),
	(200, 'PvP Shing Jea Tunic', 'Necromancer Shing Jea armor', 'Chest Armor', '-'),
	(201, 'PvP Shing Jea Gloves', 'Necromancer Shing Jea armor', 'Hands Armor', '-'),
	(202, 'PvP Shing Jea Leggings', 'Necromancer Shing Jea armor', 'Legs Armor', '-'),
	(203, 'PvP Krytan Shoes', 'Elementalist Krytan armor', 'Footwear', '-'),
	(204, 'PvP Krytan Robes', 'Elementalist Krytan armor', 'Chest Armor', '-'),
	(205, 'PvP Krytan Gloves', 'Elementalist Krytan armor', 'Hands Armor', '-'),
	(206, 'PvP Krytan Leggings', 'Elementalist Krytan armor', 'Legs Armor', '-'),
	(207, 'PvP Canthan Shoes', 'Elementalist Canthan armor', 'Footwear', '-'),
	(208, 'PvP Canthan Robes', 'Elementalist Canthan armor', 'Chest Armor', '-'),
	(209, 'PvP Canthan Gloves', 'Elementalist Canthan armor', 'Hands Armor', '-'),
	(210, 'PvP Canthan Leggings', 'Elementalist Canthan armor', 'Legs Armor', '-'),
	(211, 'PvP Shing Jea Shoes', 'Elementalist Shing Jea armor', 'Footwear', '-'),
	(212, 'PvP Shing Jea Robes', 'Elementalist Shing Jea armor', 'Chest Armor', '-'),
	(213, 'PvP Shing Jea Gloves', 'Elementalist Shing Jea armor', 'Hands Armor', '-'),
	(214, 'PvP Shing Jea Leggings', 'Elementalist Shing Jea armor', 'Legs Armor', '-'),
	(215, 'PvP Canthan Sandals', 'Monk Canthan armor', 'Footwear', '-'),
	(216, 'PvP Canthan Vestments', 'Monk Canthan armor', 'Chest Armor', '-'),
	(217, 'PvP Canthan Handwraps', 'Monk Canthan armor', 'Hands Armor', '-'),
	(218, 'PvP Canthan Pants', 'Monk Canthan armor', 'Legs Armor', '-'),
	(219, 'PvP Krytan Sandals', 'Monk Krytan armor', 'Footwear', '-'),
	(220, 'PvP Krytan Vestments', 'Monk Krytan armor', 'Chest Armor', '-'),
	(221, 'PvP Krytan Handwraps', 'Monk Krytan armor', 'Hands Armor', '-'),
	(222, 'PvP Krytan Pants', 'Monk Krytan armor', 'Legs Armor', '-'),
	(223, 'PvP Shing Jea Sandals', 'Monk Shing Jea armor', 'Footwear', '-'),
	(224, 'PvP Shing Jea Vestments', 'Monk Shing Jea armor', 'Chest Armor', '-'),
	(225, 'PvP Shing Jea Handwraps', 'Monk Shing Jea armor', 'Hands Armor', '-'),
	(226, 'PvP Shing Jea Pants', 'Monk Shing Jea armor', 'Legs Armor', '-'),
	(227, 'PvP Krytan Boots', 'Warrior Krytan armor', 'Footwear', '-'),
	(228, 'PvP Krytan Cuirass', 'Warrior Krytan armor', 'Chest Armor', '-'),
	(229, 'PvP Krytan Gauntlets', 'Warrior Krytan armor', 'Hands Armor', '-'),
	(230, 'PvP Krytan Leggings', 'Warrior Krytan armor', 'Legs Armor', '-'),
	(231, 'PvP Shing Jea Boots', 'Warrior Shing Jea armor', 'Footwear', '-'),
	(232, 'PvP Shing Jea Cuirass', 'Warrior Shing Jea armor', 'Chest Armor', '-'),
	(233, 'PvP Shing Jea Gauntlets', 'Warrior Shing Jea armor', 'Hands Armor', '-'),
	(234, 'PvP Shing Jea Leggings', 'Warrior Shing Jea armor', 'Legs Armor', '-'),
	(235, 'PvP Canthan Boots', 'Warrior Canthan armor', 'Footwear', '-'),
	(236, 'PvP Canthan Cuirass', 'Warrior Canthan armor', 'Chest Armor', '-'),
	(237, 'PvP Canthan Gauntlets', 'Warrior Canthan armor', 'Hands Armor', '-'),
	(238, 'PvP Canthan Leggings', 'Warrior Canthan armor', 'Legs Armor', '-'),
	(239, 'PvP Canthan Boots', 'Ranger Canthan armor', 'Footwear', '-'),
	(240, 'PvP Canthan Vest', 'Ranger Canthan armor', 'Chest Armor', '-'),
	(241, 'PvP Canthan Gloves', 'Ranger Canthan armor', 'Hands Armor', '-'),
	(242, 'PvP Canthan Leggings', 'Ranger Canthan armor', 'Legs Armor', '-'),
	(243, 'PvP Shing Jea Boots', 'Ranger Shing Jea armor', 'Footwear', '-'),
	(244, 'PvP Shing Jea Vest', 'Ranger Shing Jea armor', 'Chest Armor', '-'),
	(245, 'PvP Shing Jea Gloves', 'Ranger Shing Jea armor', 'Hands Armor', '-'),
	(246, 'PvP Shing Jea Leggings', 'Ranger Shing Jea armor', 'Legs Armor', '-'),
	(247, 'PvP Krytan Boots', 'Ranger Krytan armor', 'Footwear', '-'),
	(248, 'PvP Krytan Vest', 'Ranger Krytan armor', 'Chest Armor', '-'),
	(249, 'PvP Krytan Gloves', 'Ranger Krytan armor', 'Hands Armor', '-'),
	(250, 'PvP Krytan Leggings', 'Ranger Krytan armor', 'Legs Armor', '-'),
	(251, 'PvP Canthan Shoes', 'Ritualist Canthan armor', 'Footwear', '-'),
	(252, 'PvP Canthan Raiment', 'Ritualist Canthan armor', 'Chest Armor', '-'),
	(253, 'PvP Canthan Bangles', 'Ritualist Canthan armor', 'Hands Armor', '-'),
	(254, 'PvP Canthan Leggings', 'Ritualist Canthan armor', 'Legs Armor', '-'),
	(255, 'PvP Exotic Shoes', 'Ritualist Exotic armor', 'Footwear', '-'),
	(256, 'PvP Exotic Raiment', 'Ritualist Exotic armor', 'Chest Armor', '-'),
	(257, 'PvP Exotic Bangles', 'Ritualist Exotic armor', 'Hands Armor', '-'),
	(258, 'PvP Exotic Leggings', 'Ritualist Exotic armor', 'Legs Armor', '-'),
	(259, 'PvP Imperial Shoes', 'Ritualist Imperial armor', 'Footwear', '-'),
	(260, 'PvP Imperial Raiment', 'Ritualist Imperial armor', 'Chest Armor', '-'),
	(261, 'PvP Imperial Bangles', 'Ritualist Imperial armor', 'Hands Armor', '-'),
	(262, 'PvP Imperial Leggings', 'Ritualist Imperial armor', 'Legs Armor', '-'),
	(263, 'PvP Shing Jea Shoes', 'Ritualist Shing Jea armor', 'Footwear', '-'),
	(264, 'PvP Shing Jea Raiment', 'Ritualist Shing Jea armor', 'Chest Armor', '-'),
	(265, 'PvP Shing Jea Bangles', 'Ritualist Shing Jea armor', 'Hands Armor', '-'),
	(266, 'PvP Shing Jea Leggings', 'Ritualist Shing Jea armor', 'Legs Armor', '-'),
	(267, 'PvP Seitung Shoes', 'Ritualist Seitung armor', 'Footwear', '-'),
	(268, 'PvP Seitung Raiment', 'Ritualist Seitung armor', 'Chest Armor', '-'),
	(269, 'PvP Seitung Bangles', 'Ritualist Seitung armor', 'Hands Armor', '-'),
	(270, 'PvP Seitung Leggings', 'Ritualist Seitung armor', 'Legs Armor', '-'),
	(271, 'PvP Bladed Mask', 'Assassin Seitung armor', 'Headgear', '-'),
	(272, 'PvP Keen Mask', 'Assassin Canthan armor', 'Headgear', '-'),
	(273, 'PvP Deadly Mask', 'Assassin Shing Jea armor', 'Headgear', '-'),
	(274, 'PvP Shadow Mask', 'Assassin Imperial armor', 'Headgear', '-'),
	(275, 'PvP Communing Headwrap', 'Ritualist Seitung armor', 'Headgear', '-'),
	(276, 'PvP Summoning Headwrap', 'Ritualist Canthan armor', 'Headgear', '-'),
	(277, 'PvP Restoring Headwrap', 'Ritualist Shing Jea armor', 'Headgear', '-'),
	(278, 'PvP Channeling Headwrap', 'Ritualist Imperial armor', 'Headgear', '-'),
	(279, 'PvP Daggers', 'Dirks', 'Daggers', 'Piercing Dmg'),
	(280, 'PvP Communing Focus', 'Eerie Focus', 'Focus Item', 'Energy'),
	(281, 'PvP Spawning Focus', 'Ceremonial Cauldron', 'Focus Item', 'Energy'),
	(282, 'PvP Restoration Focus', 'Writhing Focus', 'Focus Item', 'Energy'),
	(283, 'PvP Channeling Focus', 'Channeling Focus', 'Focus Item', 'Energy'),
	(284, 'PvP Communing Scepter', 'Eerie Rod', 'Wand', 'Dark Dmg'),
	(285, 'PvP Spawning Scepter', 'Spawning Wand', 'Wand', 'Lightning Dmg'),
	(286, 'PvP Channeling Scepter', 'Ritualist Cane', 'Wand', 'Lightning Dmg'),
	(287, 'PvP Communing Staff', 'Communing Staff', 'Staff', 'Dark Dmg'),
	(288, 'PvP Spawning Staff', 'Spawning Staff', 'Staff', 'Lightning Dmg'),
	(289, 'PvP Channeling Staff', 'Channeling Staff', 'Staff', 'Lightning Dmg'),
	(290, 'PvP Reaper Hood', 'Dervish Elonian armor', 'Headgear', '-'),
	(291, 'PvP Mystic Hood', 'Dervish Istani armor', 'Headgear', '-'),
	(292, 'PvP Dunewalker Hood', 'Dervish Sunspear armor', 'Headgear', '-'),
	(293, 'PvP Windwalker Hood', 'Dervish Elonian armor', 'Headgear', '-'),
	(294, 'PvP Elonian Shoes', 'Dervish Elonian armor', 'Footwear', '-'),
	(295, 'PvP Elonian Robes', 'Dervish Elonian armor', 'Chest Armor', '-'),
	(296, 'PvP Elonian Vambraces', 'Dervish Elonian armor', 'Hands Armor', '-'),
	(297, 'PvP Elonian Leggings', 'Dervish Elonian armor', 'Legs Armor', '-'),
	(298, 'PvP Istani Shoes', 'Dervish Istani armor', 'Footwear', '-'),
	(299, 'PvP Istani Robes', 'Dervish Istani armor', 'Chest Armor', '-'),
	(300, 'PvP Istani Vambraces', 'Dervish Istani armor', 'Hands Armor', '-'),
	(301, 'PvP Istani Leggings', 'Dervish Istani armor', 'Legs Armor', '-'),
	(302, 'PvP Sunspear Shoes', 'Dervish Sunspear armor', 'Footwear', '-'),
	(303, 'PvP Sunspear Robes', 'Dervish Sunspear armor', 'Chest Armor', '-'),
	(304, 'PvP Sunspear Vambraces', 'Dervish Sunspear armor', 'Hands Armor', '-'),
	(305, 'PvP Sunspear Leggings', 'Dervish Sunspear armor', 'Legs Armor', '-'),
	(306, 'PvP Spear Crest', 'Paragon headgear', 'Headgear', '-'),
	(307, 'PvP Exalted Crest', 'Paragon headgear', 'Headgear', '-'),
	(308, 'PvP Vocal Crest', 'Paragon headgear', 'Headgear', '-'),
	(309, 'PvP Command Crest', 'Paragon headgear', 'Headgear', '-'),
	(310, 'PvP Istani Sandals', 'Paragon Istani armor', 'Footwear', '-'),
	(311, 'PvP Istani Raiment', 'Paragon Istani armor', 'Chest Armor', '-'),
	(312, 'PvP Istani Armguards', 'Paragon Istani armor', 'Hands Armor', '-'),
	(313, 'PvP Istani Leggings', 'Paragon Istani armor', 'Legs Armor', '-'),
	(314, 'PvP Sunspear Sandals', 'Paragon Sunspear armor', 'Footwear', '-'),
	(315, 'PvP Sunspear Raiment', 'Paragon Sunspear armor', 'Chest Armor', '-'),
	(316, 'PvP Sunspear Armguards', 'Paragon Sunspear armor', 'Hands Armor', '-'),
	(317, 'PvP Sunspear Leggings', 'Paragon Sunspear armor', 'Legs Armor', '-'),
	(318, 'PvP Elonian Sandals', 'Paragon Elonian armor', 'Footwear', '-'),
	(319, 'PvP Elonian Raiment', 'Paragon Elonian armor', 'Chest Armor', '-'),
	(320, 'PvP Elonian Armguards', 'Paragon Elonian armor', 'Hands Armor', '-'),
	(321, 'PvP Elonian Leggings', 'Paragon Elonian armor', 'Legs Armor', '-'),
	(322, 'PvP Scythe', 'Suntouched Scythe', 'Scythe', 'Slashing Dmg'),
	(323, 'PvP Motivation Shield', 'Daedal Shield', 'Shield', 'Armor'),
	(324, 'PvP Command Shield', 'Heraldic Shield', 'Shield', 'Armor'),
	(325, 'PvP Spear', 'Suntouched Spear', 'Spear', 'Piercing Dmg'),
	(326, 'PvP Arcane Scepter', 'Arcane Scepter', 'Wand', 'Chaos Dmg'),
	(327, 'PvP Cane', 'Cane', 'Wand', 'Chaos Dmg'),
	(328, 'PvP Crimson Claw Scepter', 'Crimson Claw Scepter', 'Wand', 'Dark Dmg'),
	(329, 'PvP Voltaic Wand', 'Voltaic Wand', 'Wand', 'Chaos Dmg'),
	(330, 'PvP Holy Rod', 'Eternal Flame Wand', 'Wand', 'Holy Dmg'),
	(331, 'PvP Holy Rod', 'Protective Wand', 'Wand', 'Holy Dmg'),
	(332, 'PvP Arcane Staff', 'Arcane Staff', 'Staff', 'Chaos Dmg'),
	(333, 'PvP Scrying Glass Staff', 'Scrying Glass Staff', 'Staff', 'Chaos Dmg'),
	(334, 'PvP Soul Spire', 'Soul Spire', 'Staff', 'Dark Dmg'),
	(335, 'PvP Ether Staff', 'Ether Staff', 'Staff', 'Chaos Dmg'),
	(336, 'PvP Holy Staff', 'Holy Branch', 'Staff', 'Holy Dmg'),
	(337, 'PvP Holy Staff', 'Protective Staff', 'Staff', 'Holy Dmg'),
	(338, 'PvP Restoration Scepter', 'Shamanic Wand', 'Wand', 'Dark Dmg'),
	(339, 'PvP Restoration Staff', 'Restoration Staff', 'Staff', 'Dark Dmg');
