CREATE TABLE IF NOT EXISTS `gw1_modifierdesc_en` (
	`id`      SMALLINT(3) UNSIGNED NOT NULL,
	`name`    TINYTEXT             NOT NULL,
	`desc`    TEXT                 NOT NULL,
	`base`    TINYTEXT             NOT NULL,
	`ext`     TINYTEXT             NOT NULL,
	PRIMARY KEY (`id`)
)
	ENGINE = InnoDB
	DEFAULT CHARSET = utf8mb4
	COLLATE = utf8mb4_bin;

INSERT INTO `gw1_modifierdesc_en` (`id`, `name`, `desc`, `base`, `ext`) VALUES
	(1, 'Icy Axe Haft', '%s Cold Dmg', 'Axe', 'Icy'),
	(2, 'Ebon Axe Haft', '%s Earth Dmg', 'Axe', 'Ebon'),
	(3, 'Shocking Axe Haft', '%s Lightning Dmg', 'Axe', 'Shocking'),
	(4, 'Fiery Axe Haft', '%s Fire Dmg', 'Axe', 'Fiery'),
	(5, 'Icy Bow String', '%s Cold Dmg', 'Bow', 'Icy'),
	(6, 'Ebon Bow String', '%s Earth Dmg', 'Bow', 'Ebon'),
	(7, 'Shocking Bow String', '%s Lightning Dmg', 'Bow', 'Shocking'),
	(8, 'Fiery Bow String', '%s Fire Dmg', 'Bow', 'Fiery'),
	(9, 'Icy Hammer Haft', '%s Cold Dmg', 'Hammer', 'Icy'),
	(10, 'Ebon Hammer Haft', '%s Earth Dmg', 'Hammer', 'Ebon'),
	(11, 'Shocking Hammer Haft', '%s Lightning Dmg', 'Hammer', 'Shocking'),
	(12, 'Fiery Hammer Haft', '%s Fire Dmg', 'Hammer', 'Fiery'),
	(13, 'Icy Sword Hilt', '%s Cold Dmg', 'Sword', 'Icy'),
	(14, 'Ebon Sword Hilt', '%s Earth Dmg', 'Sword', 'Ebon'),
	(15, 'Shocking Sword Hilt', '%s Lightning Dmg', 'Sword', 'Shocking'),
	(16, 'Fiery Sword Hilt', '%s Fire Dmg', 'Sword', 'Fiery'),
	(17, 'Furious Axe Haft', 'Double Adrenaline on hit (Chance: 10%)', 'Axe', 'Furious'),
	(18, 'Furious Hammer Haft', 'Double Adrenaline on hit (Chance: 10%)', 'Hammer', 'Furious'),
	(19, 'Furious Sword Hilt', 'Double Adrenaline on hit (Chance: 10%)', 'Sword', 'Furious'),
	(22, 'Rune of Minor Fast Casting', 'Fast Casting +1 (Non-stacking)', 'Mesmer Armor', 'Minor Fast Casting'),
	(23, 'Rune of Minor Domination Magic', 'Domination Magic +1 (Non-stacking)', 'Mesmer Armor', 'Minor Domination Magic'),
	(24, 'Rune of Minor Illusion Magic', 'Illusion Magic +1 (Non-stacking)', 'Mesmer Armor', 'Minor Illusion Magic'),
	(25, 'Rune of Minor Inspiration Magic', 'Inspiration Magic +1 (Non-stacking)', 'Mesmer Armor', 'Minor Inspiration Magic'),
	(26, 'Rune of Minor Blood Magic', 'Blood Magic +1 (Non-stacking)', 'Necromancer Armor', 'Minor Blood Magic'),
	(27, 'Rune of Minor Death Magic', 'Death Magic +1 (Non-stacking)', 'Necromancer Armor', 'Minor Death Magic'),
	(28, 'Rune of Minor Curses', 'Curses +1 (Non-stacking)', 'Necromancer Armor', 'Minor Curses'),
	(29, 'Rune of Minor Soul Reaping', 'Soul Reaping +1 (Non-stacking)', 'Necromancer Armor', 'Minor Soul Reaping'),
	(30, 'Rune of Minor Energy Storage', 'Energy Storage +1 (Non-stacking)', 'Elementalist Armor', 'Minor Energy Storage'),
	(31, 'Rune of Minor Fire Magic', 'Fire Magic +1 (Non-stacking)', 'Elementalist Armor', 'Minor Fire Magic'),
	(32, 'Rune of Minor Air Magic', 'Air Magic +1 (Non-stacking)', 'Elementalist Armor', 'Minor Air Magic'),
	(33, 'Rune of Minor Earth Magic', 'Earth Magic +1 (Non-stacking)', 'Elementalist Armor', 'Minor Earth Magic'),
	(34, 'Rune of Minor Water Magic', 'Water Magic +1 (Non-stacking)', 'Elementalist Armor', 'Minor Water Magic'),
	(35, 'Rune of Minor Healing Prayers', 'Healing Prayers +1 (Non-stacking)', 'Monk Armor', 'Minor Healing Prayers'),
	(36, 'Rune of Minor Smiting Prayers', 'Smiting Prayers +1 (Non-stacking)', 'Monk Armor', 'Minor Smiting Prayers'),
	(37, 'Rune of Minor Protection Prayers', 'Protection Prayers +1 (Non-stacking)', 'Monk Armor', 'Minor Protection Prayers'),
	(38, 'Rune of Minor Divine Favor', 'Divine Favor +1 (Non-stacking)', 'Monk Armor', 'Minor Divine Favor'),
	(39, 'Rune of Minor Tactics', 'Tactics +1 (Non-stacking)', 'Warrior Armor', 'Minor Tactics'),
	(40, 'Rune of Minor Strength', 'Strength +1 (Non-stacking)', 'Warrior Armor', 'Minor Strength'),
	(41, 'Rune of Minor Axe Mastery', 'Axe Mastery +1 (Non-stacking)', 'Warrior Armor', 'Minor Axe Mastery'),
	(42, 'Rune of Minor Hammer Mastery', 'Hammer Mastery +1 (Non-stacking)', 'Warrior Armor', 'Minor Hammer Mastery'),
	(43, 'Rune of Minor Swordsmanship', 'Swordsmanship +1 (Non-stacking)', 'Warrior Armor', 'Minor Swordsmanship'),
	(44, 'Rune of Minor Wilderness Survival', 'Wilderness Survival +1 (Non-stacking)', 'Ranger Armor', 'Minor Wilderness Survival'),
	(45, 'Rune of Minor Expertise', 'Expertise +1 (Non-stacking)', 'Ranger Armor', 'Minor Expertise'),
	(46, 'Rune of Minor Beast Mastery', 'Beast Mastery +1 (Non-stacking)', 'Ranger Armor', 'Minor Beast Mastery'),
	(47, 'Rune of Minor Marksmanship', 'Marksmanship +1 (Non-stacking)', 'Ranger Armor', 'Minor Marksmanship'),
	(48, 'Rune of Major Fast Casting', 'Fast Casting +2 (Non-stacking)|Health -35', 'Mesmer Armor', 'Major Fast Casting'),
	(49, 'Rune of Major Domination Magic', 'Domination Magic +2 (Non-stacking)|Health -35', 'Mesmer Armor', 'Major Domination Magic'),
	(50, 'Rune of Major Illusion Magic', 'Illusion Magic +2 (Non-stacking)|Health -35', 'Mesmer Armor', 'Major Illusion Magic'),
	(51, 'Rune of Major Inspiration Magic', 'Inspiration Magic +2 (Non-stacking)|Health -35', 'Mesmer Armor', 'Major Inspiration Magic'),
	(52, 'Rune of Major Blood Magic', 'Blood Magic +2 (Non-stacking)|Health -35', 'Necromancer Armor', 'Major Blood Magic'),
	(53, 'Rune of Major Death Magic', 'Death Magic +2 (Non-stacking)|Health -35', 'Necromancer Armor', 'Major Death Magic'),
	(54, 'Rune of Major Curses', 'Curses +2 (Non-stacking)|Health -35', 'Necromancer Armor', 'Major Curses'),
	(55, 'Rune of Major Soul Reaping', 'Soul Reaping +2 (Non-stacking)|Health -35', 'Necromancer Armor', 'Major Soul Reaping'),
	(56, 'Rune of Major Energy Storage', 'Energy Storage +2 (Non-stacking)|Health -35', 'Elementalist Armor', 'Major Energy Storage'),
	(57, 'Rune of Major Fire Magic', 'Fire Magic +2 (Non-stacking)|Health -35', 'Elementalist Armor', 'Major Fire Magic'),
	(58, 'Rune of Major Air Magic', 'Air Magic +2 (Non-stacking)|Health -35', 'Elementalist Armor', 'Major Air Magic'),
	(59, 'Rune of Major Earth Magic', 'Earth Magic +2 (Non-stacking)|Health -35', 'Elementalist Armor', 'Major Earth Magic'),
	(60, 'Rune of Major Water Magic', 'Water Magic +2 (Non-stacking)|Health -35', 'Elementalist Armor', 'Major Water Magic'),
	(61, 'Rune of Major Healing Prayers', 'Healing Prayers +2 (Non-stacking)|Health -35', 'Monk Armor', 'Major Healing Prayers'),
	(62, 'Rune of Major Smiting Prayers', 'Smiting Prayers +2 (Non-stacking)|Health -35', 'Monk Armor', 'Major Smiting Prayers'),
	(63, 'Rune of Major Protection Prayers', 'Protection Prayers +2 (Non-stacking)|Health -35', 'Monk Armor', 'Major Protection Prayers'),
	(64, 'Rune of Major Divine Favor', 'Divine Favor +2 (Non-stacking)|Health -35', 'Monk Armor', 'Major Divine Favor'),
	(65, 'Rune of Major Tactics', 'Tactics +2 (Non-stacking)|Health -35', 'Warrior Armor', 'Major Tactics'),
	(66, 'Rune of Major Strength', 'Strength +2 (Non-stacking)|Health -35', 'Warrior Armor', 'Major Strength'),
	(67, 'Rune of Major Axe Mastery', 'Axe Mastery +2 (Non-stacking)|Health -35', 'Warrior Armor', 'Major Axe Mastery'),
	(68, 'Rune of Major Hammer Mastery', 'Hammer Mastery +2 (Non-stacking)|Health -35', 'Warrior Armor', 'Major Hammer Mastery'),
	(69, 'Rune of Major Swordsmanship', 'Swordsmanship +2 (Non-stacking)|Health -35', 'Warrior Armor', 'Major Swordsmanship'),
	(70, 'Rune of Major Wilderness Survival', 'Wilderness Survival +2 (Non-stacking)|Health -35', 'Ranger Armor', 'Major Wilderness Survival'),
	(71, 'Rune of Major Expertise', 'Expertise +2 (Non-stacking)|Health -35', 'Ranger Armor', 'Major Expertise'),
	(72, 'Rune of Major Beast Mastery', 'Beast Mastery +2 (Non-stacking)|Health -35', 'Ranger Armor', 'Major Beast Mastery'),
	(73, 'Rune of Major Marksmanship', 'Marksmanship +2 (Non-stacking)|Health -35', 'Ranger Armor', 'Major Marksmanship'),
	(74, 'Rune of Superior Fast Casting', 'Fast Casting +3 (Non-stacking)|Health -75', 'Mesmer Armor', 'Superior Fast Casting'),
	(75, 'Rune of Superior Domination Magic', 'Domination Magic +3 (Non-stacking)|Health -75', 'Mesmer Armor', 'Superior Domination Magic'),
	(76, 'Rune of Superior Illusion Magic', 'Illusion Magic +3 (Non-stacking)|Health -75', 'Mesmer Armor', 'Superior Illusion Magic'),
	(77, 'Rune of Superior Inspiration Magic', 'Inspiration Magic +3 (Non-stacking)|Health -75', 'Mesmer Armor', 'Superior Inspiration Magic'),
	(78, 'Rune of Superior Blood Magic', 'Blood Magic +3 (Non-stacking)|Health -75', 'Necromancer Armor', 'Superior Blood Magic'),
	(79, 'Rune of Superior Death Magic', 'Death Magic +3 (Non-stacking)|Health -75', 'Necromancer Armor', 'Superior Death Magic'),
	(80, 'Rune of Superior Curses', 'Curses +3 (Non-stacking)|Health -75', 'Necromancer Armor', 'Superior Curses'),
	(81, 'Rune of Superior Soul Reaping', 'Soul Reaping +3 (Non-stacking)|Health -75', 'Necromancer Armor', 'Superior Soul Reaping'),
	(82, 'Rune of Superior Energy Storage', 'Energy Storage +3 (Non-stacking)|Health -75', 'Elementalist Armor', 'Superior Energy Storage'),
	(83, 'Rune of Superior Fire Magic', 'Fire Magic +3 (Non-stacking)|Health -75', 'Elementalist Armor', 'Superior Fire Magic'),
	(84, 'Rune of Superior Air Magic', 'Air Magic +3 (Non-stacking)|Health -75', 'Elementalist Armor', 'Superior Air Magic'),
	(85, 'Rune of Superior Earth Magic', 'Earth Magic +3 (Non-stacking)|Health -75', 'Elementalist Armor', 'Superior Earth Magic'),
	(86, 'Rune of Superior Water Magic', 'Water Magic +3 (Non-stacking)|Health -75', 'Elementalist Armor', 'Superior Water Magic'),
	(87, 'Rune of Superior Healing Prayers', 'Healing Prayers +3 (Non-stacking)|Health -75', 'Monk Armor', 'Superior Healing Prayers'),
	(88, 'Rune of Superior Smiting Prayers', 'Smiting Prayers +3 (Non-stacking)|Health -75', 'Monk Armor', 'Superior Smiting Prayers'),
	(89, 'Rune of Superior Protection Prayers', 'Protection Prayers +3 (Non-stacking)|Health -75', 'Monk Armor', 'Superior Protection Prayers'),
	(90, 'Rune of Superior Divine Favor', 'Divine Favor +3 (Non-stacking)|Health -75', 'Monk Armor', 'Superior Divine Favor'),
	(91, 'Rune of Superior Tactics', 'Tactics +3 (Non-stacking)|Health -75', 'Warrior Armor', 'Superior Tactics'),
	(92, 'Rune of Superior Strength', 'Strength +3 (Non-stacking)|Health -75', 'Warrior Armor', 'Superior Strength'),
	(93, 'Rune of Superior Axe Mastery', 'Axe Mastery +3 (Non-stacking)|Health -75', 'Warrior Armor', 'Superior Axe Mastery'),
	(94, 'Rune of Superior Hammer Mastery', 'Hammer Mastery +3 (Non-stacking)|Health -75', 'Warrior Armor', 'Superior Hammer Mastery'),
	(95, 'Rune of Superior Swordsmanship', 'Swordsmanship +3 (Non-stacking)|Health -75', 'Warrior Armor', 'Superior Swordsmanship'),
	(96, 'Rune of Superior Wilderness Survival', 'Wilderness Survival +3 (Non-stacking)|Health -75', 'Ranger Armor', 'Superior Wilderness Survival'),
	(97, 'Rune of Superior Expertise', 'Expertise +3 (Non-stacking)|Health -75', 'Ranger Armor', 'Superior Expertise'),
	(98, 'Rune of Superior Beast Mastery', 'Beast Mastery +3 (Non-stacking)|Health -75', 'Ranger Armor', 'Superior Beast Mastery'),
	(99, 'Rune of Superior Marksmanship', 'Marksmanship +3 (Non-stacking)|Health -75', 'Ranger Armor', 'Superior Marksmanship'),
	(100, 'Defensive Staff Head', 'Armor +5', 'Staff', 'Defensive'),
	(101, 'Barbed Axe Haft', 'Lengthens Bleeding duration on foes by 33% (Stacking)', 'Axe', 'Barbed'),
	(102, 'Barbed Sword Hilt', 'Lengthens Bleeding duration on foes by 33% (Stacking)', 'Sword', 'Barbed'),
	(103, 'Crippling Axe Haft', 'Lengthens Crippled duration on foes by 33% (Stacking)', 'Axe', 'Crippling'),
	(104, 'Crippling Sword Hilt', 'Lengthens Crippled duration on foes by 33% (Stacking)', 'Sword', 'Crippling'),
	(105, 'Cruel Axe Haft', 'Lengthens Deep Wound duration on foes by 33% (Stacking)', 'Axe', 'Cruel'),
	(106, 'Cruel Hammer Haft', 'Lengthens Deep Wound duration on foes by 33% (Stacking)', 'Hammer', 'Cruel'),
	(107, 'Cruel Sword Hilt', 'Lengthens Deep Wound duration on foes by 33% (Stacking)', 'Sword', 'Cruel'),
	(108, 'Insightful Staff Head', 'Energy +5', 'Staff', 'Insightful'),
	(109, 'Hale Staff Head', 'Health +30', 'Staff', 'Hale'),
	(110, 'Poisonous Axe Haft', 'Lengthens Poison duration on foes by 33% (Stacking)', 'Axe', 'Poisonous'),
	(111, 'Poisonous Bow String', 'Lengthens Poison duration on foes by 33% (Stacking)', 'Bow', 'Poisonous'),
	(112, 'Poisonous Sword Hilt', 'Lengthens Poison duration on foes by 33% (Stacking)', 'Sword', 'Poisonous'),
	(113, 'Heavy Axe Haft', 'Lengthens Weakness duration on foes by 33% (Stacking)', 'Axe', 'Heavy'),
	(114, 'Heavy Hammer Haft', 'Lengthens Weakness duration on foes by 33% (Stacking)', 'Hammer', 'Heavy'),
	(115, 'Zealous Axe Haft', 'Energy gain on hit: 1|Energy regeneration: -1', 'Axe', 'Zealous'),
	(116, 'Zealous Hammer Haft', 'Energy gain on hit: 1|Energy regeneration: -1', 'Hammer', 'Zealous'),
	(117, 'Zealous Bow String', 'Energy gain on hit: 1|Energy regeneration: -1', 'Bow', 'Zealous'),
	(118, 'Zealous Sword Hilt', 'Energy gain on hit: 1|Energy regeneration: -1', 'Sword', 'Zealous'),
	(119, 'Vampiric Axe Haft', 'Life stealing: 3|Health regeneration: -1', 'Axe', 'Vampiric'),
	(120, 'Vampiric Hammer Haft', 'Life stealing: 5|Health regeneration: -1', 'Hammer', 'Vampiric'),
	(121, 'Vampiric Bow String', 'Life stealing: 5|Health regeneration: -1', 'Bow', 'Vampiric'),
	(122, 'Vampiric Sword Hilt', 'Life stealing: 3|Health regeneration: -1', 'Sword', 'Vampiric'),
	(123, 'Rune of Minor Mysticism', 'Mysticism +1 (Non-stacking)', 'Dervish Armor', 'Minor Mysticism'),
	(124, 'Rune of Minor Earth Prayers', 'Earth Prayers +1 (Non-stacking)', 'Dervish Armor', 'Minor Earth Prayers'),
	(125, 'Rune of Minor Scythe Mastery', 'Scythe Mastery +1 (Non-stacking)', 'Dervish Armor', 'Minor Scythe Mastery'),
	(126, 'Rune of Minor Wind Prayers', 'Wind Prayers +1 (Non-stacking)', 'Dervish Armor', 'Minor Wind Prayers'),
	(127, 'Axe Grip of Defense', 'Armor +5', 'Axe', 'Defense'),
	(128, 'Bow Grip of Defense', 'Armor +5', 'Bow', 'Defense'),
	(129, 'Axe Grip of Warding', 'Armor +7 (vs. elemental damage)', 'Axe', 'Warding'),
	(130, 'Bow Grip of Warding', 'Armor +7 (vs. elemental damage)', 'Bow', 'Warding'),
	(131, 'Hammer Grip of Warding', 'Armor +7 (vs. elemental damage)', 'Hammer', 'Warding'),
	(132, 'Staff Wrapping of Warding', 'Armor +7 (vs. elemental damage)', 'Staff', 'Warding'),
	(133, 'Sword Pommel of Warding', 'Armor +7 (vs. elemental damage)', 'Sword', 'Warding'),
	(134, 'Hammer Grip of Defense', 'Armor +5', 'Hammer', 'Defense'),
	(135, 'Axe Grip of Shelter', 'Armor +7 (vs. physical damage)', 'Axe', 'Shelter'),
	(136, 'Bow Grip of Shelter', 'Armor +7 (vs. physical damage)', 'Bow', 'Shelter'),
	(137, 'Hammer Grip of Shelter', 'Armor +7 (vs. physical damage)', 'Hammer', 'Shelter'),
	(138, 'Staff Wrapping of Shelter', 'Armor +7 (vs. physical damage)', 'Staff', 'Shelter'),
	(139, 'Sword Pommel of Shelter', 'Armor +7 (vs. physical damage)', 'Sword', 'Shelter'),
	(140, 'Staff Wrapping of Defense', 'Armor +5', 'Staff', 'Defense'),
	(141, 'Sword Pommel of Defense', 'Armor +5', 'Sword', 'Defense'),
	(142, 'Axe Grip of Fortitude', 'Health +30', 'Axe', 'Fortitude'),
	(143, 'Bow Grip of Fortitude', 'Health +30', 'Bow', 'Fortitude'),
	(144, 'Hammer Grip of Fortitude', 'Health +30', 'Hammer', 'Fortitude'),
	(145, 'Staff Wrapping of Fortitude', 'Health +30', 'Staff', 'Fortitude'),
	(146, 'Sword Pommel of Fortitude', 'Health +30', 'Sword', 'Fortitude'),
	(147, 'Axe Grip of Enchanting', 'Enchantments last 20% longer', 'Axe', 'Enchanting'),
	(148, 'Bow Grip of Enchanting', 'Enchantments last 20% longer', 'Bow', 'Enchanting'),
	(149, 'Hammer Grip of Enchanting', 'Enchantments last 20% longer', 'Hammer', 'Enchanting'),
	(150, 'Staff Wrapping of Enchanting', 'Enchantments last 20% longer', 'Staff', 'Enchanting'),
	(151, 'Sword Pommel of Enchanting', 'Enchantments last 20% longer', 'Sword', 'Enchanting'),
	(152, 'Axe Grip of Mastery', 'Attribute +1 (20% chance while using skills)', 'Axe', 'Mastery'),
	(153, 'Bow Grip of Mastery', 'Attribute +1 (20% chance while using skills)', 'Bow', 'Mastery'),
	(154, 'Hammer Grip of Mastery', 'Attribute +1 (20% chance while using skills)', 'Hammer', 'Mastery'),
	(155, 'Sword Pommel of Mastery', 'Attribute +1 (20% chance while using skills)', 'Sword', 'Mastery'),
	(156, 'Rune of Minor Vigor', 'Health +30 (Non-stacking)', 'Armor', 'Minor Vigor'),
	(157, 'Rune of Major Vigor', 'Health +41 (Non-stacking)', 'Armor', 'Major Vigor'),
	(158, 'Rune of Superior Vigor', 'Health +50 (Non-stacking)', 'Armor', 'Superior Vigor'),
	(159, 'Rune of Minor Absorption', 'Reduces physical damage by 1 (Non-stacking)', 'Warrior Armor', 'Minor Absorption'),
	(160, 'Rune of Major Absorption', 'Reduces physical damage by 2 (Non-stacking)', 'Warrior Armor', 'Major Absorption'),
	(161, 'Rune of Superior Absorption', 'Reduces physical damage by 3 (Non-stacking)', 'Warrior Armor', 'Superior Absorption'),
	(162, 'Rune of Minor Critical Strikes', 'Critical Strikes +1 (Non-stacking)', 'Assassin Armor', 'Minor Critical Strikes'),
	(163, 'Rune of Minor Dagger Mastery', 'Dagger Mastery +1 (Non-stacking)', 'Assassin Armor', 'Minor Dagger Mastery'),
	(164, 'Rune of Minor Deadly Arts', 'Deadly Arts +1 (Non-stacking)', 'Assassin Armor', 'Minor Deadly Arts'),
	(165, 'Rune of Minor Shadow Arts', 'Shadow Arts +1 (Non-stacking)', 'Assassin Armor', 'Minor Shadow Arts'),
	(166, 'Rune of Minor Channeling Magic', 'Channeling Magic +1 (Non-stacking)', 'Ritualist Armor', 'Minor Channeling Magic'),
	(167, 'Rune of Minor Restoration Magic', 'Restoration Magic +1 (Non-stacking)', 'Ritualist Armor', 'Minor Restoration Magic'),
	(168, 'Rune of Minor Communing', 'Communing +1 (Non-stacking)', 'Ritualist Armor', 'Minor Communing'),
	(169, 'Rune of Minor Spawning Power', 'Spawning Power +1 (Non-stacking)', 'Ritualist Armor', 'Minor Spawning Power'),
	(170, 'Rune of Major Critical Strikes', 'Critical Strikes +2 (Non-stacking)|Health -35', 'Assassin Armor', 'Major Critical Strikes'),
	(171, 'Rune of Major Dagger Mastery', 'Dagger Mastery +2 (Non-stacking)|Health -35', 'Assassin Armor', 'Major Dagger Mastery'),
	(172, 'Rune of Major Deadly Arts', 'Deadly Arts +2 (Non-stacking)|Health -35', 'Assassin Armor', 'Major Deadly Arts'),
	(173, 'Rune of Major Shadow Arts', 'Shadow Arts +2 (Non-stacking)|Health -35', 'Assassin Armor', 'Major Shadow Arts'),
	(174, 'Rune of Major Channeling Magic', 'Channeling Magic +2 (Non-stacking)|Health -35', 'Ritualist Armor', 'Major Channeling Magic'),
	(175, 'Rune of Major Restoration Magic', 'Restoration Magic +2 (Non-stacking)|Health -35', 'Ritualist Armor', 'Major Restoration Magic'),
	(176, 'Rune of Major Communing', 'Communing +2 (Non-stacking)|Health -35', 'Ritualist Armor', 'Major Communing'),
	(177, 'Rune of Major Spawning Power', 'Spawning Power +2 (Non-stacking)|Health -35', 'Ritualist Armor', 'Major Spawning Power'),
	(178, 'Rune of Superior Critical Strikes', 'Critical Strikes +3 (Non-stacking)|Health -75', 'Assassin Armor', 'Superior Critical Strikes'),
	(179, 'Rune of Superior Dagger Mastery', 'Dagger Mastery +3 (Non-stacking)|Health -75', 'Assassin Armor', 'Superior Dagger Mastery'),
	(180, 'Rune of Superior Deadly Arts', 'Deadly Arts +3 (Non-stacking)|Health -75', 'Assassin Armor', 'Superior Deadly Arts'),
	(181, 'Rune of Superior Shadow Arts', 'Shadow Arts +3 (Non-stacking)|Health -75', 'Assassin Armor', 'Superior Shadow Arts'),
	(182, 'Rune of Superior Channeling Magic', 'Channeling Magic +3 (Non-stacking)|Health -75', 'Ritualist Armor', 'Superior Channeling Magic'),
	(183, 'Rune of Superior Restoration Magic', 'Restoration Magic +3 (Non-stacking)|Health -75', 'Ritualist Armor', 'Superior Restoration Magic'),
	(184, 'Rune of Superior Communing', 'Communing +3 (Non-stacking)|Health -75', 'Ritualist Armor', 'Superior Communing'),
	(185, 'Rune of Superior Spawning Power', 'Spawning Power +3 (Non-stacking)|Health -75', 'Ritualist Armor', 'Superior Spawning Power'),
	(186, 'Icy Dagger Tang', '%s Cold Dmg', 'Daggers', 'Icy'),
	(187, 'Ebon Dagger Tang', '%s Earth Dmg', 'Daggers', 'Ebon'),
	(188, 'Fiery Dagger Tang', '%s Fire Dmg', 'Daggers', 'Fiery'),
	(189, 'Shocking Dagger Tang', '%s Lightning Dmg', 'Daggers', 'Shocking'),
	(190, 'Zealous Dagger Tang', 'Energy gain on hit: 1|Energy regeneration: -1', 'Daggers', 'Zealous'),
	(191, 'Vampiric Dagger Tang', 'Life stealing: 3|Health regeneration: -1', 'Daggers', 'Vampiric'),
	(192, 'Barbed Dagger Tang', 'Lengthens Bleeding duration on foes by 33% (Stacking)', 'Daggers', 'Barbed'),
	(193, 'Crippling Dagger Tang', 'Lengthens Crippled duration on foes by 33% (Stacking)', 'Daggers', 'Crippling'),
	(194, 'Cruel Dagger Tang', 'Lengthens Deep Wound duration on foes by 33% (Stacking)', 'Daggers', 'Cruel'),
	(195, 'Poisonous Dagger Tang', 'Lengthens Poison duration on foes by 33% (Stacking)', 'Daggers', 'Poisonous'),
	(196, 'Silencing Dagger Tang', 'Lengthens Dazed duration on foes by 33% (Stacking)', 'Daggers', 'Silencing'),
	(197, 'Furious Dagger Tang', 'Double Adrenaline on hit (Chance: 10%)', 'Daggers', 'Furious'),
	(198, 'Rune of Minor Leadership', 'Leadership +1 (Non-stacking)', 'Paragon Armor', 'Minor Leadership'),
	(199, 'Dagger Handle of Mastery', 'Attribute +1 (20% chance while using skills)', 'Daggers', 'Mastery'),
	(200, 'Dagger Handle of Defense', 'Armor +5', 'Daggers', 'Defense'),
	(201, 'Dagger Handle of Shelter', 'Armor +7 (vs. physical damage)', 'Daggers', 'Shelter'),
	(202, 'Dagger Handle of Warding', 'Armor +7 (vs. elemental damage)', 'Daggers', 'Warding'),
	(203, 'Dagger Handle of Enchanting', 'Enchantments last 20% longer', 'Daggers', 'Enchanting'),
	(204, 'Dagger Handle of Fortitude', 'Health +30', 'Daggers', 'Fortitude'),
	(205, 'Barbed Bow String', 'Lengthens Bleeding duration on foes by 33% (Stacking)', 'Bow', 'Barbed'),
	(206, 'Crippling Bow String', 'Lengthens Crippled duration on foes by 33% (Stacking)', 'Bow', 'Crippling'),
	(207, 'Silencing Bow String', 'Lengthens Dazed duration on foes by 33% (Stacking)', 'Bow', 'Silencing'),
	(208, 'Sundering Axe Haft', 'Armor penetration +20% (Chance: 20%)', 'Axe', 'Sundering'),
	(209, 'Sundering Bow String', 'Armor penetration +20% (Chance: 20%)', 'Bow', 'Sundering'),
	(210, 'Sundering Hammer Haft', 'Armor penetration +20% (Chance: 20%)', 'Hammer', 'Sundering'),
	(211, 'Sundering Sword Hilt', 'Armor penetration +20% (Chance: 20%)', 'Sword', 'Sundering'),
	(212, 'Sundering Dagger Tang', 'Armor penetration +20% (Chance: 20%)', 'Daggers', 'Sundering'),
	(213, 'Rune of Minor Motivation', 'Motivation +1 (Non-stacking)', 'Paragon Armor', 'Minor Motivation'),
	(214, 'Rune of Minor Command', 'Command +1 (Non-stacking)', 'Paragon Armor', 'Minor Command'),
	(215, 'Rune of Minor Spear Mastery', 'Spear Mastery +1 (Non-stacking)', 'Paragon Armor', 'Minor Spear Mastery'),
	(216, 'Rune of Major Mysticism', 'Mysticism +2 (Non-stacking)|Health -35', 'Dervish Armor', 'Major Mysticism'),
	(217, 'Rune of Major Earth Prayers', 'Earth Prayers +2 (Non-stacking)|Health -35', 'Dervish Armor', 'Major Earth Prayers'),
	(218, 'Rune of Major Scythe Mastery', 'Scythe Mastery +2 (Non-stacking)|Health -35', 'Dervish Armor', 'Major Scythe Mastery'),
	(219, 'Rune of Major Wind Prayers', 'Wind Prayers +2 (Non-stacking)|Health -35', 'Dervish Armor', 'Major Wind Prayers'),
	(220, 'Rune of Major Leadership', 'Leadership +2 (Non-stacking)|Health -35', 'Paragon Armor', 'Major Leadership'),
	(221, 'Rune of Major Motivation', 'Motivation +2 (Non-stacking)|Health -35', 'Paragon Armor', 'Major Motivation'),
	(222, 'Rune of Major Command', 'Command +2 (Non-stacking)|Health -35', 'Paragon Armor', 'Major Command'),
	(223, 'Rune of Major Spear Mastery', 'Spear Mastery +2 (Non-stacking)|Health -35', 'Paragon Armor', 'Major Spear Mastery'),
	(224, 'Rune of Superior Mysticism', 'Mysticism +3 (Non-stacking)|Health -75', 'Dervish Armor', 'Superior Mysticism'),
	(225, 'Rune of Superior Earth Prayers', 'Earth Prayers +3 (Non-stacking)|Health -75', 'Dervish Armor', 'Superior Earth Prayers'),
	(226, 'Rune of Superior Scythe Mastery', 'Scythe Mastery +3 (Non-stacking)|Health -75', 'Dervish Armor', 'Superior Scythe Mastery'),
	(227, 'Rune of Superior Wind Prayers', 'Wind Prayers +3 (Non-stacking)|Health -75', 'Dervish Armor', 'Superior Wind Prayers'),
	(228, 'Rune of Superior Leadership', 'Leadership +3 (Non-stacking)|Health -75', 'Paragon Armor', 'Superior Leadership'),
	(229, 'Rune of Superior Motivation', 'Motivation +3 (Non-stacking)|Health -75', 'Paragon Armor', 'Superior Motivation'),
	(230, 'Rune of Superior Command', 'Command +3 (Non-stacking)|Health -75', 'Paragon Armor', 'Superior Command'),
	(231, 'Rune of Superior Spear Mastery', 'Spear Mastery +3 (Non-stacking)|Health -75', 'Paragon Armor', 'Superior Spear Mastery'),
	(232, 'Icy Scythe Snathe', '%s Cold Dmg', 'Scythe', 'Icy'),
	(233, 'Ebon Scythe Snathe', '%s Earth Dmg', 'Scythe', 'Ebon'),
	(234, 'Zealous Scythe Snathe', 'Energy gain on hit: 1|Energy regeneration: -1', 'Scythe', 'Zealous'),
	(235, 'Vampiric Scythe Snathe', 'Life stealing: 3|Health regeneration: -1', 'Scythe', 'Vampiric'),
	(236, 'Sundering Scythe Snathe', 'Armor penetration +20% (Chance: 20%)', 'Scythe', 'Sundering'),
	(237, 'Barbed Scythe Snathe', 'Lengthens Bleeding duration on foes by 33% (Stacking)', 'Scythe', 'Barbed'),
	(238, 'Crippling Scythe Snathe', 'Lengthens Crippled duration on foes by 33% (Stacking)', 'Scythe', 'Crippling'),
	(239, 'Cruel Scythe Snathe', 'Lengthens Deep Wound duration on foes by 33% (Stacking)', 'Scythe', 'Cruel'),
	(240, 'Furious Scythe Snathe', 'Double Adrenaline on hit (Chance: 10%)', 'Scythe', 'Furious'),
	(241, 'Poisonous Scythe Snathe', 'Lengthens Poison duration on foes by 33% (Stacking)', 'Scythe', 'Poisonous'),
	(242, 'Heavy Scythe Snathe', 'Lengthens Weakness duration on foes by 33% (Stacking)', 'Scythe', 'Heavy'),
	(243, 'Scythe Grip of Mastery', 'Attribute +1 (20% chance while using skills)', 'Scythe', 'Mastery'),
	(244, 'Scythe Grip of Defense', 'Armor +5', 'Scythe', 'Defense'),
	(245, 'Scythe Grip of Shelter', 'Armor +7 (vs. physical damage)', 'Scythe', 'Shelter'),
	(246, 'Scythe Grip of Warding', 'Armor +7 (vs. elemental damage)', 'Scythe', 'Warding'),
	(247, 'Scythe Grip of Enchanting', 'Enchantments last 20% longer', 'Scythe', 'Enchanting'),
	(248, 'Scythe Grip of Fortitude', 'Health +30', 'Scythe', 'Fortitude'),
	(249, 'Fiery Spearhead', '%s Fire Dmg', 'Spear', 'Fiery'),
	(250, 'Shocking Spearhead', '%s Lightning Dmg', 'Spear', 'Shocking'),
	(251, 'Zealous Spearhead', 'Energy gain on hit: 1|Energy regeneration: -1', 'Spear', 'Zealous'),
	(252, 'Vampiric Spearhead', 'Life stealing: 3|Health regeneration: -1', 'Spear', 'Vampiric'),
	(253, 'Sundering Spearhead', 'Armor penetration +20% (Chance: 20%)', 'Spear', 'Sundering'),
	(254, 'Barbed Spearhead', 'Lengthens Bleeding duration on foes by 33% (Stacking)', 'Spear', 'Barbed'),
	(255, 'Crippling Spearhead', 'Lengthens Crippled duration on foes by 33% (Stacking)', 'Spear', 'Crippling'),
	(256, 'Cruel Spearhead', 'Lengthens Deep Wound duration on foes by 33% (Stacking)', 'Spear', 'Cruel'),
	(257, 'Furious Spearhead', 'Double Adrenaline on hit (Chance: 10%)', 'Spear', 'Furious'),
	(258, 'Poisonous Spearhead', 'Lengthens Poison duration on foes by 33% (Stacking)', 'Spear', 'Poisonous'),
	(259, 'Silencing Spearhead', 'Lengthens Dazed duration on foes by 33% (Stacking)', 'Spear', 'Silencing'),
	(260, 'Heavy Spearhead', 'Lengthens Weakness duration on foes by 33% (Stacking)', 'Spear', 'Heavy'),
	(261, 'Spear Grip of Mastery', 'Attribute +1 (20% chance while using skills)', 'Spear', 'Mastery'),
	(262, 'Spear Grip of Defense', 'Armor +5', 'Spear', 'Defense'),
	(263, 'Spear Grip of Shelter', 'Armor +7 (vs. physical damage)', 'Spear', 'Shelter'),
	(264, 'Spear Grip of Warding', 'Armor +7 (vs. elemental damage)', 'Spear', 'Warding'),
	(265, 'Spear Grip of Enchanting', 'Enchantments last 20% longer', 'Spear', 'Enchanting'),
	(266, 'Spear Grip of Fortitude', 'Health +30', 'Spear', 'Fortitude'),
	(267, 'Focus Core of Endurance', 'Health +45 (while in a Stance)', 'Focus Item', 'Endurance'),
	(268, 'Focus Core of Valor', 'Health +60 (while Hexed)', 'Focus Item', 'Valor'),
	(269, 'Fiery Scythe Snathe', '%s Fire Dmg', 'Scythe', 'Fiery'),
	(270, 'Shocking Scythe Snathe', '%s Lightning Dmg', 'Scythe', 'Shocking'),
	(271, 'Icy Spearhead', '%s Cold Dmg', 'Spear', 'Icy'),
	(272, 'Ebon Spearhead', '%s Earth Dmg', 'Spear', 'Ebon'),
	(273, 'Swift Staff Head', 'Halves casting time of spells (Chance: 10%)', 'Staff', 'Swift'),
	(274, 'Staff Wrapping of Devotion', 'Health +45 (while Enchanted)', 'Staff', 'Devotion'),
	(275, 'Staff Wrapping of Endurance', 'Health +45 (while in a Stance)', 'Staff', 'Endurance'),
	(276, 'Staff Wrapping of Valor', 'Health +60 (while Hexed)', 'Staff', 'Valor'),
	(277, 'Inscription: "Let the Memory Live Again"', 'Halves skill recharge of spells (Chance: 10%)', 'Martial Weapons', ''),
	(278, 'Inscription: "Have Faith"', 'Energy +5 (while Enchanted)', 'Caster Weapons', ''),
	(279, 'Inscription: "Don\'t call it a comeback!"', 'Energy +7 (while Health is below 50%)', 'Caster Weapons', ''),
	(280, 'Inscription: "I am Sorrow"', 'Energy +7 (while Hexed)', 'Caster Weapons', ''),
	(281, 'Inscription: "Don\'t Think Twice"', 'Halves casting time of spells (Chance: 10%)', 'Weapons', ''),
	(282, 'Inscription: "Too Much Information"', 'Damage +15% (vs. Hexed foes)', 'Weapons', ''),
	(283, 'Inscription: "Guided by Fate"', 'Damage +15% (while Enchanted)', 'Weapons', ''),
	(284, 'Inscription: "Soundness of Mind"', 'Reduces Dazed duration on you by 20% (Stacking)', 'Focus Items or Shields', ''),
	(285, 'Inscription: "Only the Strong Survive"', 'Reduces Weakness duration on you by 20% (Stacking)', 'Focus Items or Shields', ''),
	(286, 'Inscription: "Don\'t Fear the Reaper"', 'Damage +20% (while Hexed)', 'Weapons', ''),
	(287, 'Inscription: "Dance with Death"', 'Damage +15% (while in a Stance)', 'Weapons', ''),
	(288, 'Inscription: "Brawn over Brains"', 'Damage +15%|Energy -5', 'Weapons', ''),
	(289, 'Inscription: "To the Pain!"', 'Damage +15%|Armor -10 (while attacking)', 'Weapons', ''),
	(290, 'Survivor Insignia', '%s Health +15 (on chest armor)|Health +10 (on leg armor)|Health +5 (on other armor)|||Health +15||Health +10||Health +5', 'Armor', 'Survivor'),
	(291, 'Radiant Insignia', '%s Energy +3 (on chest armor)|Energy +2 (on leg armor)|Energy +1 (on other armor)|||Energy +3||Energy +2||Energy +1', 'Armor', 'Radiant'),
	(292, 'Stalwart Insignia', 'Armor +10 (vs. physical damage)', 'Armor', 'Stalwart'),
	(293, 'Brawler\'s Insignia', 'Armor +10 (while attacking)', 'Armor', 'Brawler\'s'),
	(294, 'Blessed Insignia', 'Armor +10 (while affected by an Enchantment Spell)', 'Armor', 'Blessed'),
	(295, 'Herald\'s Insignia', 'Armor +10 (while holding an item)', 'Armor', 'Herald\'s'),
	(296, 'Sentry\'s Insignia', 'Armor +10 (while in a Stance)', 'Armor', 'Sentry\'s'),
	(297, 'Vanguard\'s Insignia', 'Armor +10 (vs. physical damage)|Armor +10 (vs. Blunt damage)', 'Assassin Armor', 'Vanguard\'s'),
	(298, 'Infiltrator\'s Insignia', 'Armor +10 (vs. physical damage)|Armor +10 (vs. Piercing damage)', 'Assassin Armor', 'Infiltrator\'s'),
	(299, 'Saboteur\'s Insignia', 'Armor +10 (vs. physical damage)|Armor +10 (vs. Slashing damage)', 'Assassin Armor', 'Saboteur\'s'),
	(300, 'Nightstalker\'s Insignia', 'Armor +15 (while attacking)', 'Assassin Armor', 'Nightstalker\'s'),
	(301, 'Virtuoso\'s Insignia', 'Armor +15 (while activating skills)', 'Mesmer Armor', 'Virtuoso\'s'),
	(302, 'Bloodstained Insignia', 'Reduces casting time of spells that exploit corpses by 25% (Non-stacking)', 'Necromancer Armor', 'Bloodstained'),
	(303, 'Tormentor\'s Insignia', '%s Holy damage you receive increased by 6 (on chest armor)|Holy damage you receive increased by 4 (on leg armor)|Holy damage you receive increased by 2 (on other armor)|Armor +10|||Holy damage you receive increased by 6|Armor +10||Holy damage you receive increased by 4|Armor +10||Holy damage you receive increased by 2|Armor +10', 'Necromancer Armor', 'Tormentor\'s'),
	(304, 'Bonelace Insignia', 'Armor +15 (vs. Piercing damage)', 'Necromancer Armor', 'Bonelace'),
	(305, 'Minion Master\'s Insignia', 'Armor +5 (while you control 1 or more minions)|Armor +5 (while you control 3 or more minions)|Armor +5 (while you control 5 or more minions)', 'Necromancer Armor', 'Minion'),
	(306, 'Blighter\'s Insignia', 'Armor +20 (while affected by a Hex Spell)', 'Necromancer Armor', 'Blighter\'s'),
	(307, 'Hydromancer\'s Insignia', 'Armor +10 (vs. elemental damage)|Armor +10 (vs. Cold damage)', 'Elementalist Armor', 'Hydromancer\'s'),
	(308, 'Geomancer\'s Insignia', 'Armor +10 (vs. elemental damage)|Armor +10 (vs. Earth damage)', 'Elementalist Armor', 'Geomancer\'s'),
	(309, 'Pyromancer\'s Insignia', 'Armor +10 (vs. elemental damage)|Armor +10 (vs. Fire damage)', 'Elementalist Armor', 'Pyromancer\'s'),
	(310, 'Aeromancer\'s Insignia', 'Armor +10 (vs. elemental damage)|Armor +10 (vs. Lightning damage)', 'Elementalist Armor', 'Aeromancer\'s'),
	(311, 'Wanderer\'s Insignia', 'Armor +10 (vs. elemental damage)', 'Monk Armor', 'Wanderer\'s'),
	(312, 'Disciple\'s Insignia', 'Armor +15 (while affected by a Condition)', 'Monk Armor', 'Disciple\'s'),
	(313, 'Knight\'s Insignia', 'Received physical damage -3', 'Warrior Armor', 'Knight\'s'),
	(314, 'Lieutenant\'s Insignia', 'Reduces Hex durations on you by 20% and damage dealt by you by 5% (Non-stacking)|Armor -20', 'Warrior Armor', 'Lieutenant\'s'),
	(315, 'Stonefist Insignia', 'Increases knockdown time on foes by 1 second. (Maximum: 3 seconds) (Non-stacking)', 'Warrior Armor', 'Stonefist'),
	(316, 'Dreadnought Insignia', 'Armor +10 (vs. elemental damage)', 'Warrior Armor', 'Dreadnought'),
	(317, 'Sentinel\'s Insignia', 'Armor +20 (Requires 13 Strength, vs. elemental damage)', 'Warrior Armor', 'Sentinel\'s'),
	(318, 'Frostbound Insignia', 'Armor +15 (vs. Cold damage)', 'Ranger Armor', 'Frostbound'),
	(319, 'Pyrebound Insignia', 'Armor +15 (vs. Fire damage)', 'Ranger Armor', 'Pyrebound'),
	(320, 'Stormbound Insignia', 'Armor +15 (vs. Lightning damage)', 'Ranger Armor', 'Stormbound'),
	(321, 'Scout\'s Insignia', 'Armor +10 (while using a Preparation)', 'Ranger Armor', 'Scout\'s'),
	(322, 'Shaman\'s Insignia', 'Armor +5 (while you control 1 or more Spirits)|Armor +5 (while you control 2 or more Spirits)|Armor +5 (while you control 3 or more Spirits)', 'Ritualist Armor', 'Shaman\'s'),
	(323, 'Ghost Forge Insignia', 'Armor +15 (while affected by a Weapon Spell)', 'Ritualist Armor', 'Ghost'),
	(324, 'Mystic\'s Insignia', 'Armor +15 (while activating skills)', 'Ritualist Armor', 'Mystic\'s'),
	(325, 'Inscription: "Faith is My Shield"', 'Armor +5 (while Enchanted)', 'Focus Items', ''),
	(326, 'Inscription: "Live for Today"', 'Energy +15|Energy regeneration -1', 'Focus Items', ''),
	(327, 'Inscription: "Serenity Now"', 'Halves skill recharge of spells (Chance: 10%)', 'Focus Items', ''),
	(328, 'Inscription: "Forget Me Not"', 'Halves skill recharge of spells of item\'s attribute (Chance: 20%)', 'Focus Items', ''),
	(329, 'Inscription: "I have the power!"', 'Energy +5', 'Martial Weapons', ''),
	(330, 'Inscription: "Luck of the Draw"', 'Received physical damage -5 (Chance: 20%)', 'Focus Items or Shields', ''),
	(331, 'Inscription: "Sheltered by Faith"', 'Received physical damage -2 (while Enchanted)', 'Focus Items or Shields', ''),
	(332, 'Inscription: "Nothing to Fear"', 'Received physical damage -3 (while Hexed)', 'Focus Items or Shields', ''),
	(333, 'Inscription: "Run For Your Life!"', 'Received physical damage -2 (while in a Stance)', 'Focus Items or Shields', ''),
	(334, 'Inscription: "Master of My Domain"', 'Item\'s attribute +1 (Chance: 20%)', 'Focus Items or Shields', ''),
	(335, 'Inscription: "Aptitude not Attitude"', 'Halves casting time of spells of item\'s attribute (Chance: 20%)', 'Caster Weapons', ''),
	(336, 'Inscription: "Seize the Day"', 'Energy +15|Energy regeneration -1', 'Caster Weapons', ''),
	(337, 'Inscription: "Hale and Hearty"', 'Energy +5 (while Health is above 50%)', 'Caster Weapons', ''),
	(338, 'Inscription: "Strength and Honor"', 'Damage +15% (while Health is above 50%)', 'Weapons', ''),
	(339, 'Inscription: "Vengeance is Mine"', 'Damage +20% (while Health is below 50%)', 'Weapons', ''),
	(340, 'Focus Core of Fortitude', 'Health +30', 'Focus Item', 'Fortitude'),
	(341, 'Focus Core of Devotion', 'Health +45 (while Enchanted)', 'Focus Item', 'Devotion'),
	(342, 'Focus Core of Swiftness', 'Halves casting time of spells (Chance: 10%)', 'Focus Item', 'Swiftness'),
	(343, 'Focus Core of Aptitude', 'Halves casting time of item\'s attribute spells (Chance: 20%)', 'Focus Item', 'Aptitude'),
	(344, 'Wand Wrapping of Quickening', 'Halves skill recharge of spells (Chance: 10%)', 'Wand', 'Quickening'),
	(345, 'Wand Wrapping of Memory', 'Halves skill recharge on spells of item\'s attribute (Chance: 20%)', 'Wand', 'Memory'),
	(346, 'Shield Handle of Fortitude', 'Health +30', 'Shield', 'Fortitude'),
	(347, 'Shield Handle of Devotion', 'Health +45 (while Enchanted)', 'Shield', 'Devotion'),
	(348, 'Shield Handle of Endurance', 'Health +45 (while in a Stance)', 'Shield', 'Endurance'),
	(349, 'Shield Handle of Valor', 'Health +60 (while Hexed)', 'Shield', 'Valor'),
	(350, 'Adept Staff Head', 'Halves casting time of spells of item\'s attribute (Chance: 20%)', 'Staff', 'Adept'),
	(351, 'Staff Wrapping of Mastery', 'Attribute +1 (20% chance while using skills)', 'Staff', 'Mastery'),
	(352, 'Rune of Attunement', 'Energy +2', 'Armor', 'Attunement'),
	(353, 'Rune of Vitae', 'Health +10', 'Armor', 'Vitae'),
	(354, 'Rune of Recovery', 'Reduces Dazed duration on you by 20% (Non-stacking)|Reduces Deep Wound duration on you by 20% (Non-stacking)', 'Armor', 'Recovery'),
	(355, 'Rune of Restoration', 'Reduces Bleeding duration on you by 20% (Stacking)|Reduces Crippled duration on you by 20% (Non-stacking)', 'Armor', 'Restoration'),
	(356, 'Rune of Clarity', 'Reduces Blind duration on you by 20% (Non-stacking)|Reduces Weakness duration on you by 20% (Non-stacking)', 'Armor', 'Clarity'),
	(357, 'Rune of Purity', 'Reduces Disease duration on you by 20% (Non-stacking)|Reduces Poison duration on you by 20% (Non-stacking)', 'Armor', 'Purity'),
	(358, 'Artificer\'s Insignia', 'Armor +3 (for each equipped Signet)', 'Mesmer Armor', 'Artificer\'s'),
	(359, 'Prodigy\'s Insignia', 'Armor +5 (while recharging 1 or more Skills)|Armor +5 (while recharging 3 or more Skills)|Armor +5 (while recharging 5 or more Skills)', 'Mesmer Armor', 'Prodigy\'s'),
	(360, 'Undertaker\'s Insignia', 'Armor +5 (while health is below 80%)|Armor +5 (while health is below 60%)|Armor +5 (while health is below 40%)|Armor +5 (while health is below 20%)', 'Necromancer Armor', 'Undertaker\'s'),
	(361, 'Prismatic Insignia', 'Armor +5 (requires 9 Air Magic)|Armor +5 (requires 9 Earth Magic)|Armor +5 (requires 9 Fire Magic)|Armor +5 (requires 9 Water Magic)', 'Elementalist Armor', 'Prismatic'),
	(362, 'Anchorite\'s Insignia', 'Armor +5 (while recharging 1 or more Skills)|Armor +5 (while recharging 3 or more Skills)|Armor +5 (while recharging 5 or more Skills)', 'Monk Armor', 'Anchorite\'s'),
	(363, 'Earthbound Insignia', 'Armor +15 (vs. Earth damage)', 'Ranger Armor', 'Earthbound'),
	(364, 'Beastmaster\'s Insignia', 'Armor +10 (while your pet is alive)', 'Ranger Armor', 'Beastmaster\'s'),
	(365, 'Windwalker Insignia', 'Armor +5 (while affected by 1 or more Enchantment Spells)|Armor +5 (while affected by 2 or more Enchantment Spells)|Armor +5 (while affected by 3 or more Enchantment Spells)|Armor +5 (while affected by 4 or more Enchantment Spells)', 'Dervish Armor', 'Windwalker'),
	(366, 'Forsaken Insignia', 'Armor +10 (while not affected by an Enchantment Spell)', 'Dervish Armor', 'Forsaken'),
	(367, 'Centurion\'s Insignia', 'Armor +10 (while affected by a Shout, Echo, or Chant)', 'Paragon Armor', 'Centurion\'s'),
	(368, 'Inscription: "Ignorance is Bliss"', 'Armor +5|Energy -5', 'Focus Items', ''),
	(369, 'Inscription: "Life is Pain"', 'Armor +5|Health -20', 'Focus Items', ''),
	(370, 'Inscription: "Man for All Seasons"', 'Armor +5 (vs. elemental damage)', 'Focus Items', ''),
	(371, 'Inscription: "Survival of the Fittest"', 'Armor +5 (vs. physical damage)', 'Focus Items', ''),
	(372, 'Inscription: "Might makes Right"', 'Armor +5 (while attacking)', 'Focus Items', ''),
	(373, 'Inscription: "Knowing is Half the Battle"', 'Armor +5 (while casting)', 'Focus Items', ''),
	(374, 'Inscription: "Down But Not Out"', 'Armor +10 (while Health is below 50%)', 'Focus Items', ''),
	(375, 'Inscription: "Hail to the King"', 'Armor +5 (while Health is above 50%)', 'Focus Items', ''),
	(376, 'Inscription: "Be Just and Fear Not"', 'Armor +10 (while Hexed)', 'Focus Items', ''),
	(377, 'Inscription: "Not the face!"', 'Armor +10 (vs. Blunt damage)', 'Focus Items or Shields', ''),
	(378, 'Inscription: "Leaf on the Wind"', 'Armor +10 (vs. Cold damage)', 'Focus Items or Shields', ''),
	(379, 'Inscription: "Like a Rolling Stone"', 'Armor +10 (vs. Earth damage)', 'Focus Items or Shields', ''),
	(380, 'Inscription: "Riders on the Storm"', 'Armor +10 (vs. Lightning damage)', 'Focus Items or Shields', ''),
	(381, 'Inscription: "Sleep Now in the Fire"', 'Armor +10 (vs. Fire damage)', 'Focus Items or Shields', ''),
	(382, 'Inscription: "Through Thick and Thin"', 'Armor +10 (vs. Piercing damage)', 'Focus Items or Shields', ''),
	(383, 'Inscription: "The Riddle of Steel"', 'Armor +10 (vs. Slashing damage)', 'Focus Items or Shields', ''),
	(384, 'Inscription: "Fear Cuts Deeper"', 'Reduces Bleeding duration on you by 20% (Stacking)', 'Focus Items or Shields', ''),
	(385, 'Inscription: "I Can See Clearly Now"', 'Reduces Blind duration on you by 20% (Stacking)', 'Focus Items or Shields', ''),
	(386, 'Inscription: "Swift as the Wind"', 'Reduces Crippled duration on you by 20% (Stacking)', 'Focus Items or Shields', ''),
	(387, 'Inscription: "Strength of Body"', 'Reduces Deep Wound duration on you by 20% (Stacking)', 'Focus Items or Shields', ''),
	(388, 'Inscription: "Cast Out the Unclean"', 'Reduces Disease duration on you by 20% (Stacking)', 'Focus Items or Shields', ''),
	(389, 'Inscription: "Pure of Heart"', 'Reduces Poison duration on you by 20% (Stacking)', 'Focus Items or Shields', '');
